const words = [
    // CHU DE 1
    // V:1-27:
    { word: 'overcome', meaning: ['vượt qua'], synonyms: 'get through', topic: 1, type: 'V' },
    { word: 'discover', meaning: ['khám phá'], synonyms: 'find out, explore', topic: 1, type: 'V' },
    { word: 'reflect', meaning: ['phản chiếu'], synonyms: 'mirror, show', topic: 1, type: 'V' },
    { word: 'struggle', meaning: ['vật lộn'], synonyms: 'fight, battle', topic: 1, type: 'V' },
    { word: 'inspire', meaning: ['truyền cảm hứng'], synonyms: 'motivate, encourage', topic: 1, type: 'V' },
    { word: 'motivate', meaning: ['tạo động lực'], synonyms: 'encourage, drive', topic: 1, type: 'V' },
    { word: 'accomplish', meaning: ['hoàn thành'], synonyms: 'achieve, complete', topic: 1, type: 'V' },
    { word: 'transform', meaning: ['biến đổi'], synonyms: 'change, convert', topic: 1, type: 'V' },
    { word: 'stimulate', meaning: ['kích thích'], synonyms: 'encourage, boost', topic: 1, type: 'V' },
    { word: 'confront', meaning: ['đối mặt'], synonyms: 'face, encounter', topic: 1, type: 'V' },
    { word: 'sacrifice', meaning: ['hy sinh'], synonyms: 'give up', topic: 1, type: 'V' },
    { word: 'challenge', meaning: ['thách thức'], synonyms: 'defy, question', topic: 1, type: 'V' },
    { word: 'pursue', meaning: ['theo đuổi'], synonyms: 'follow, seek', topic: 1, type: 'V' },
    { word: 'recognize', meaning: ['công nhận'], synonyms: 'acknowledge', topic: 1, type: 'V' },
    { word: 'adapt', meaning: ['thích nghi với'], synonyms: 'adjust', topic: 1, type: 'V' },
    { word: 'cope with', meaning: ['đối phó với'], synonyms: 'deal with', topic: 1, type: 'V' },
    { word: 'manage', meaning: ['quản lý'], synonyms: 'control, handle', topic: 1, type: 'V' },
    { word: 'strive for', meaning: ['phấn đấu cho'], synonyms: 'aim for, try hard', topic: 1, type: 'V' },
    { word: 'rebuild', meaning: ['xây dựng lại'], synonyms: 'reconstruct, restore', topic: 1, type: 'V' },
    { word: 'consolidate', meaning: ['củng cố'], synonyms: 'strengthen, build up', topic: 1, type: 'V' },
    { word: 'demonstrate', meaning: ['chứng minh'], synonyms: '', topic: 1, type: 'V' },
    { word: 'appreciate', meaning: ['trân trọng', 'đánh giá cao'], synonyms: '', topic: 1, type: 'V' },
    { word: 'survive', meaning: ['sống sót', 'tồn tại'], synonyms: 'endure, outlive', topic: 1, type: 'V' },
    { word: 'attempt', meaning: ['cố gắng', 'nỗ lực'], synonyms: '', topic: 1, type: 'V' },
    { word: 'represent', meaning: ['đại diện cho', 'biểu tượng cho'], synonyms: 'stand for, symbolize', topic: 1, type: 'V' },
    { word: 'evaluate', meaning: ['đánh giá'], synonyms: 'assess, judge, appraise', topic: 1, type: 'V' },
    { word: 'define', meaning: ['định nghĩa'], synonyms: 'describe, explain', topic: 1, type: 'V' },

    // N:1-30:
    { word: 'struggle', meaning: 'sự đấu tranh', synonyms: '', topic: 1, type: 'N' },
    { word: 'ambition', meaning: 'tham vọng', synonyms: '', topic: 1, type: 'N' },
    { word: 'challenge', meaning: 'thử thách, thách thức', synonyms: 'difficulty, obstacle, impediment', topic: 1, type: 'N' },
    { word: 'turning point', meaning: 'bước ngoặt', synonyms: 'breakthrough, milestone', topic: 1, type: 'N' },
    { word: 'inspiration', meaning: 'nguồn cảm hứng', synonyms: 'motivation, encouragement', topic: 1, type: 'N' },
    { word: 'background', meaning: 'nền tảng (xuất thân)', synonyms: 'origin, upbringing', topic: 1, type: 'N' },
    { word: 'motivation', meaning: 'động lực', synonyms: 'drive, incentive', topic: 1, type: 'N' },
    { word: 'reputation', meaning: 'danh tiếng', synonyms: 'fame, status', topic: 1, type: 'N' },
    { word: 'identity', meaning: 'bản sắc', synonyms: '', topic: 1, type: 'N' },
    { word: 'disappointment', meaning: 'sự thất vọng', synonyms: '', topic: 1, type: 'N' },
    { word: 'achievement', meaning: 'thành tựu', synonyms: 'accomplishment, success', topic: 1, type: 'N' },
    { word: 'encouragement', meaning: 'sự khích lệ', synonyms: '', topic: 1, type: 'N' },
    { word: 'destiny', meaning: 'định mệnh', synonyms: '', topic: 1, type: 'N' },
    { word: 'obstacle', meaning: 'chướng ngại', synonyms: 'barrier, hindrance, impediment', topic: 1, type: 'N' },
    { word: 'emotion', meaning: 'cảm xúc', synonyms: '', topic: 1, type: 'N' },
    { word: 'conflict', meaning: 'sự xung đột', synonyms: 'clash, disagreement', topic: 1, type: 'N' },
    { word: 'strength', meaning: 'sức mạnh', synonyms: '', topic: 1, type: 'N' },
    { word: 'honesty', meaning: 'sự trung thực', synonyms: 'integrity, truthfulness', topic: 1, type: 'N' },
    { word: 'perseverance', meaning: 'sự kiên trì', synonyms: 'persistence, determination', topic: 1, type: 'N' },
    { word: 'determination', meaning: 'sự quyết tâm', synonyms: 'tenacity, perseverance', topic: 1, type: 'N' },
    { word: 'self-confidence', meaning: 'sự tự tin', synonyms: '', topic: 1, type: 'N' },
    { word: 'forgiveness', meaning: 'sự tha thứ', synonyms: '', topic: 1, type: 'N' },
    { word: 'legacy', meaning: 'di sản', synonyms: '', topic: 1, type: 'N' },
    { word: 'purpose', meaning: 'mục đích', synonyms: '', topic: 1, type: 'N' },
    { word: 'kindness', meaning: 'lòng tốt', synonyms: 'compassion, generosity', topic: 1, type: 'N' },
    { word: 'responsibility', meaning: 'trách nhiệm', synonyms: '', topic: 1, type: 'N' },
    { word: 'empathy', meaning: 'sự đồng cảm', synonyms: 'compassion, understanding', topic: 1, type: 'N' },
    { word: 'vision', meaning: 'tầm nhìn', synonyms: 'foresight, outlook', topic: 1, type: 'N' },
    { word: 'belief', meaning: 'niềm tin', synonyms: 'conviction, faith', topic: 1, type: 'N' },
    { word: 'passion', meaning: 'đam mê', synonyms: 'enthusiasm, fervor', topic: 1, type: 'N' },
    // ADJ:1-10:
    { word: 'determined', meaning: 'quyết tâm', synonyms: 'resolute, steadfast', topic: 1, type: 'ADJ' },
    { word: 'inspirational', meaning: 'truyền cảm hứng', synonyms: 'motivating, uplifting', topic: 1, type: 'ADJ' },
    { word: 'memorable', meaning: 'đáng nhớ', synonyms: 'unforgettable, eventful', topic: 1, type: 'ADJ' },
    { word: 'successful', meaning: 'thành công', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'courageous', meaning: 'dũng cảm', synonyms: 'brave, valiant', topic: 1, type: 'ADJ' },
    { word: 'emotional', meaning: 'cảm xúc', synonyms: 'sentimental', topic: 1, type: 'ADJ' },
    { word: 'motivated', meaning: 'có động lực', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'resilient', meaning: 'kiên cường', synonyms: 'tough, adaptable', topic: 1, type: 'ADJ' },
    { word: 'hopeful', meaning: 'đầy hy vọng', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'remarkable', meaning: 'đáng chú ý', synonyms: 'extraordinary, notable, exceptional, outstanding', topic: 1, type: 'ADJ' },

    // ADJ:11-30:
    { word: 'passionate', meaning: 'đam mê', synonyms: 'enthusiastic, fervent', topic: 1, type: 'ADJ' },
    { word: 'independent', meaning: 'độc lập', synonyms: 'self-reliant, autonomous', topic: 1, type: 'ADJ' },
    { word: 'thoughtful', meaning: 'chu đáo', synonyms: 'considerate', topic: 1, type: 'ADJ' },
    { word: 'loyal', meaning: 'trung thành', synonyms: 'faithful, devoted', topic: 1, type: 'ADJ' },
    { word: 'confident', meaning: 'tự tin', synonyms: 'self-assured, assured', topic: 1, type: 'ADJ' },
    { word: 'grateful', meaning: 'biết ơn', synonyms: 'thankful, appreciative', topic: 1, type: 'ADJ' },
    { word: 'faithful', meaning: 'trung thực', synonyms: 'loyal, devoted', topic: 1, type: 'ADJ' },
    { word: 'influential', meaning: 'có ảnh hưởng', synonyms: 'powerful, persuasive', topic: 1, type: 'ADJ' },
    { word: 'supportive', meaning: 'ủng hộ', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'compassionate', meaning: 'nhân ái', synonyms: 'empathetic, kind-hearted', topic: 1, type: 'ADJ' },
    { word: 'decisive', meaning: 'quyết đoán', synonyms: 'resolute, determined', topic: 1, type: 'ADJ' },
    { word: 'reflective', meaning: 'suy tư', synonyms: 'contemplative, thoughtful', topic: 1, type: 'ADJ' },
    { word: 'generous', meaning: 'hào phóng', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'sensitive', meaning: 'nhạy cảm', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'respectful', meaning: ['tôn trọng', 'lễ phép'], synonyms: 'courteous, polite', topic: 1, type: 'ADJ' },
    { word: 'self-aware', meaning: 'tự nhận thức', synonyms: 'introspective, self-conscious', topic: 1, type: 'ADJ' },
    { word: 'rational', meaning: 'lý trí', synonyms: 'logical, reasonable, sensible', topic: 1, type: 'ADJ' },
    { word: 'gentle', meaning: 'dịu dàng', synonyms: 'kind, tender', topic: 1, type: 'ADJ' },
    { word: 'optimistic', meaning: 'lạc quan', synonyms: 'hopeful, positive', topic: 1, type: 'ADJ' },
    { word: 'fearless', meaning: 'không sợ hãi', synonyms: 'brave, bold', topic: 1, type: 'ADJ' },

    // PV:1-45:
    { word: 'earn a prize', meaning: 'giành được giải thưởng', synonyms: '', topic: 1, type: 'PV' },
    { word: 'take on', meaning: 'đảm nhận (trách nhiệm, nhiệm vụ)', synonyms: '', topic: 1, type: 'PV' },
    { word: 'pursue your dream', meaning: 'theo đuổi ước mơ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'follow in one’s footsteps', meaning: 'theo bước ai đó', synonyms: '', topic: 1, type: 'PV' },
    { word: 'strive for', meaning: 'phấn đấu vì', synonyms: '', topic: 1, type: 'PV' },
    { word: 'deal with', meaning: 'giải quyết', synonyms: 'cope with, handle, resolve, address, combat', topic: 1, type: 'PV' },
    { word: 'carry on', meaning: 'tiếp tục', synonyms: 'continue, go on, press on, press ahead', topic: 1, type: 'PV' },
    { word: 'find out', meaning: 'phát hiện ra', synonyms: 'discover, figure out, work out', topic: 1, type: 'PV' },
    { word: 'gain knowledge', meaning: 'tích lũy kiến thức', synonyms: 'acquire knowledge, absorb knowledge', topic: 1, type: 'PV' },
    { word: 'seek support', meaning: 'tìm kiếm sự hỗ trợ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'face challenge', meaning: 'đối mặt với thử thách', synonyms: 'confront, encounter', topic: 1, type: 'PV' },
    { word: 'gain recognition', meaning: 'đạt được sự công nhận', synonyms: '', topic: 1, type: 'PV' },
    { word: 'bring about', meaning: 'gây ra', synonyms: 'result in, lead to, give rise to, contribute to, allow for', topic: 1, type: 'PV' },
    { word: 'chase your passion', meaning: 'theo đuổi đam mê', synonyms: '', topic: 1, type: 'PV' },
    { word: 'make something a reality', meaning: 'biến điều gì thành hiện thực', synonyms: '', topic: 1, type: 'PV' },
    { word: 'grow up', meaning: 'lớn lên, trưởng thành', synonyms: '', topic: 1, type: 'PV' },
    { word: 'rise to stardom', meaning: 'trở nên nổi tiếng', synonyms: '', topic: 1, type: 'PV' },
    { word: 'contribute to', meaning: 'đóng góp vào', synonyms: 'add to, be part of', topic: 1, type: 'PV' },
    { word: 'set up', meaning: 'thiết lập', synonyms: 'establish, found', topic: 1, type: 'PV' },
    { word: 'look up', meaning: ['tra cứu', 'ngưỡng mộ'], synonyms: '', topic: 1, type: 'PV' },
    { word: 'face your fear', meaning: 'đối mặt với nỗi sợ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'push yourself beyond your limit', meaning: 'vượt qua giới hạn', synonyms: 'exceed your limit, step out of your comfort zone', topic: 1, type: 'PV' },
    { word: 'play an important role in', meaning: 'đóng vai trò quan trọng', synonyms: 'be instrumental in', topic: 1, type: 'PV' },
    { word: 'take a chance on', meaning: 'đánh liều với', synonyms: 'risk Ving, gamble on, take a risk', topic: 1, type: 'PV' },
    { word: 'make a difference', meaning: 'tạo ra sự khác biệt', synonyms: 'impact, change for the better', topic: 1, type: 'PV' },
    { word: 'face up to', meaning: 'đối mặt với', synonyms: 'confront with', topic: 1, type: 'PV' },
    { word: 'pick yourself up', meaning: 'đứng dậy', synonyms: 'recover from, bounce back, regain composure', topic: 1, type: 'PV' },
    { word: 'push through', meaning: 'vượt qua', synonyms: 'persevere, persist, overcome', topic: 1, type: 'PV' },
    { word: 'break through', meaning: 'đột phá', synonyms: '', topic: 1, type: 'PV' },
    { word: 'stand out', meaning: 'nổi bật', synonyms: '', topic: 1, type: 'PV' },
    { word: 'get over', meaning: 'vượt qua', synonyms: 'recover, overcome, conquer', topic: 1, type: 'PV' },
    { word: 'turn back', meaning: 'quay lại', synonyms: '', topic: 1, type: 'PV' },
    { word: 'catch up with', meaning: 'bắt kịp', synonyms: 'keep up with, keep pace with', topic: 1, type: 'PV' },
    { word: 'get through', meaning: 'vượt qua', synonyms: 'endure, survive, complete', topic: 1, type: 'PV' },
    { word: 'look out for', meaning: 'trông chừng', synonyms: 'watch out for', topic: 1, type: 'PV' },
    { word: 'come up with', meaning: 'nghĩ ra', synonyms: 'devise, invent, formulate', topic: 1, type: 'PV' },
    { word: 'put up with', meaning: 'chịu đựng', synonyms: 'tolerate, endure, bear', topic: 1, type: 'PV' },
    { word: 'fit in', meaning: 'hòa nhập', synonyms: '', topic: 1, type: 'PV' },
    { word: 'stand by', meaning: 'ủng hộ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'let go of', meaning: 'buông bỏ', synonyms: 'relinquish, abandon', topic: 1, type: 'PV' },
    { word: 'tear up', meaning: 'xúc động', synonyms: '', topic: 1, type: 'PV' },
    { word: 'back away', meaning: 'lùi lại', synonyms: 'retreat, withdraw (from), step back (from)', topic: 1, type: 'PV' },
    { word: 'run away from', meaning: 'chạy trốn', synonyms: '', topic: 1, type: 'PV' },
    { word: 'stick with', meaning: 'gắn bó với', synonyms: 'stick to sth: tuân thủ (luật/quy tắc)', topic: 1, type: 'PV' },
    { word: 'look after', meaning: 'chăm sóc', synonyms: 'care for, attend to', topic: 1, type: 'PV' },


    // CHU DE 2
    // Verb: 1-35
    { word: 'integrate', meaning: ['hòa nhập', 'hội nhập', 'tích hợp', 'kết hợp'], synonyms: 'incorporate', topic: 2, type: 'V' },
    { word: 'assimilate', meaning: 'đồng hóa', synonyms: '', topic: 2, type: 'V' },
    { word: 'embrace', meaning: 'đón nhận', synonyms: 'accept, welcome, come to terms with', topic: 2, type: 'V' },
    { word: 'recognize', meaning: 'công nhận', synonyms: 'acknowledge', topic: 2, type: 'V' },
    { word: 'preserve', meaning: 'bảo tồn', synonyms: '', topic: 2, type: 'V' },
    { word: 'celebrate', meaning: 'tôn vinh', synonyms: 'honor, observe', topic: 2, type: 'V' },
    { word: 'overcome', meaning: 'vượt qua', synonyms: 'conquer, defeat', topic: 2, type: 'V' },
    { word: 'encounter', meaning: 'bắt gặp (ai/cái gì), gặp (vấn đề)', synonyms: 'run into, come up against', topic: 2, type: 'V' },
    { word: 'represent', meaning: 'đại diện', synonyms: 'stand for, symbolize', topic: 2, type: 'V' },
    { word: 'express', meaning: 'bày tỏ', synonyms: 'convey, communicate, deliver', topic: 2, type: 'V' },

    { word: 'maintain', meaning: 'duy trì', synonyms: 'preserve, sustain', topic: 2, type: 'V' },
    { word: 'bridge', meaning: 'thu hẹp (khoảng cách)', synonyms: 'narrow, reduce the gap', topic: 2, type: 'V' },
    { word: 'misunderstand', meaning: 'hiểu sai', synonyms: 'misinterpret', topic: 2, type: 'V' },
    { word: 'unite', meaning: 'đoàn kết', synonyms: '', topic: 2, type: 'V' },
    { word: 'interact', meaning: 'tương tác', synonyms: '', topic: 2, type: 'V' },
    { word: 'discriminate', meaning: ['phân biệt đối xử', 'phân biệt (cái gì với cái gì)'], synonyms: 'differentiate, distinguish', topic: 2, type: 'V' },
    { word: 'highlight', meaning: 'nhấn mạnh', synonyms: 'emphasize, stress, underscore', topic: 2, type: 'V' },
    { word: 'emphasize', meaning: 'nhấn mạnh', synonyms: 'highlight, underline', topic: 2, type: 'V' },
    { word: 'promote', meaning: 'thúc đẩy', synonyms: 'encourage, foster, nurture', topic: 2, type: 'V' },
    { word: 'undermine', meaning: 'làm suy yếu', synonyms: 'weaken, sabotage', topic: 2, type: 'V' },

    { word: 'participate', meaning: 'tham gia vào', synonyms: 'join, engage in, partake in, take part in, be/get involved in, be part of', topic: 2, type: 'V' },
    { word: 'generalize', meaning: 'khái quát hóa', synonyms: '', topic: 2, type: 'V' },
    { word: 'encourage', meaning: 'khuyến khích', synonyms: 'inspire, motivate', topic: 2, type: 'V' },
    { word: 'observe', meaning: ['quan sát', 'tuân thủ'], synonyms: 'watch, notice, follow, comply with', topic: 2, type: 'V' },
    { word: 'compound', meaning: 'làm phức tạp', synonyms: 'worsen, exacerbate, aggravate', topic: 2, type: 'V' },
    { word: 'reinforce', meaning: 'củng cố', synonyms: 'strengthen, support', topic: 2, type: 'V' },
    { word: 'offend', meaning: 'xúc phạm', synonyms: '', topic: 2, type: 'V' },
    { word: 'conform', meaning: 'tuân theo', synonyms: 'follow, obey, observe, adhere to, abide by, stick to, comply with', topic: 2, type: 'V' },
    { word: 'reject', meaning: 'từ chối', synonyms: 'refuse, decline', topic: 2, type: 'V' },
    { word: 'interpret', meaning: 'diễn giải', synonyms: 'explain, translate', topic: 2, type: 'V' },

    { word: 'adapt', meaning: ['thích nghi'], synonyms: 'adjust, modify', topic: 2, type: 'V' },
    { word: 'transfer', meaning: ['chuyển giao'], synonyms: '', topic: 2, type: 'V' },
    { word: 'navigate', meaning: ['điều hướng'], synonyms: 'steer, manage', topic: 2, type: 'V' },
    { word: 'overlook', meaning: ['bỏ qua'], synonyms: '', topic: 2, type: 'V' },
    { word: 'exclude', meaning: ['loại trừ'], synonyms: 'leave out, eliminate', topic: 2, type: 'V' },
    //noun : 1-43
    { word: 'ethnicity', meaning: ['dân tộc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'heritage', meaning: ['di sản'], synonyms: '', topic: 2, type: 'N' },
    { word: 'assimilation', meaning: ['sự đồng hóa'], synonyms: '', topic: 2, type: 'N' },
    { word: 'integration', meaning: ['sự hòa nhập'], synonyms: '', topic: 2, type: 'N' },
    { word: 'tradition', meaning: ['truyền thống'], synonyms: '', topic: 2, type: 'N' },
    { word: 'custom', meaning: ['phong tục'], synonyms: '', topic: 2, type: 'N' },
    { word: 'multiculturalism', meaning: ['sự đa văn hóa'], synonyms: 'cultural diversity, pluralism', topic: 2, type: 'N' },
    { word: 'identity', meaning: ['bản sắc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'background', meaning: ['hoàn cảnh'], synonyms: '', topic: 2, type: 'N' },
    { word: 'norm', meaning: ['chuẩn mực'], synonyms: '', topic: 2, type: 'N' },
    { word: 'stereotype', meaning: ['định kiến'], synonyms: '', topic: 2, type: 'N' },
    { word: 'prejudice', meaning: ['thành kiến'], synonyms: 'bias, discrimination', topic: 2, type: 'N' },
    { word: 'discrimination', meaning: ['sự phân biệt đối xử'], synonyms: 'prejudice, unfairness', topic: 2, type: 'N' },
    { word: 'tolerance', meaning: ['sự khoan dung'], synonyms: 'acceptance, open-mindedness', topic: 2, type: 'N' },
    { word: 'ritual', meaning: ['nghi lễ'], synonyms: '', topic: 2, type: 'N' },
    { word: 'minority', meaning: ['thiểu số'], synonyms: '', topic: 2, type: 'N' },
    { word: 'majority', meaning: ['đa số'], synonyms: '', topic: 2, type: 'N' },
    { word: 'ethnocentrism', meaning: ['chủ nghĩa dân tộc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'barrier', meaning: ['rào cản'], synonyms: 'obstacle, hurdle, impediment', topic: 2, type: 'N' },
    { word: 'diversity', meaning: ['sự đa dạng'], synonyms: 'variety', topic: 2, type: 'N' },
    { word: 'globalization', meaning: ['toàn cầu hóa'], synonyms: '', topic: 2, type: 'N' },
    { word: 'hospitality', meaning: ['lòng hiếu khách'], synonyms: '', topic: 2, type: 'N' },
    { word: 'race', meaning: ['chủng tộc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'religion', meaning: ['tôn giáo'], synonyms: '', topic: 2, type: 'N' },
    { word: 'perspective', meaning: ['quan điểm'], synonyms: 'opinion, viewpoint, outlook, point of view', topic: 2, type: 'N' },
    { word: 'cultural shock', meaning: ['sốc văn hóa'], synonyms: '', topic: 2, type: 'N' },
    { word: 'unity', meaning: ['sự đoàn kết'], synonyms: 'solidarity, harmony', topic: 2, type: 'N' },
    { word: 'interaction', meaning: ['sự tương tác'], synonyms: '', topic: 2, type: 'N' },
    { word: 'community', meaning: ['cộng đồng'], synonyms: '', topic: 2, type: 'N' },
    { word: 'misunderstanding', meaning: ['sự hiểu nhầm'], synonyms: '', topic: 2, type: 'N' },
    { word: 'symbolism', meaning: ['biểu tượng học'], synonyms: '', topic: 2, type: 'N' },
    { word: 'patriotism', meaning: ['chủ nghĩa yêu nước'], synonyms: 'nationalism, altruism', topic: 2, type: 'N' },
    { word: 'xenophobia', meaning: ['sự kỳ thị người nước ngoài'], synonyms: '', topic: 2, type: 'N' },
    { word: 'respect', meaning: ['sự tôn trọng'], synonyms: '', topic: 2, type: 'N' },
    { word: 'acceptance', meaning: ['sự chấp nhận'], synonyms: 'approval, recognition', topic: 2, type: 'N' },
    { word: 'representation', meaning: ['sự đại diện'], synonyms: '', topic: 2, type: 'N' },
    { word: 'inclusion', meaning: ['sự bao gồm'], synonyms: '', topic: 2, type: 'N' },
    { word: 'coexistence', meaning: ['sự cùng tồn tại'], synonyms: '', topic: 2, type: 'N' },
    { word: 'nationality', meaning: ['quốc tịch'], synonyms: '', topic: 2, type: 'N' },
    { word: 'belonging', meaning: ['sự thuộc về'], synonyms: '', topic: 2, type: 'N' },
    { word: 'civilization', meaning: ['nền văn minh'], synonyms: '', topic: 2, type: 'N' },
    { word: 'convention', meaning: ['hội nghị'], synonyms: '', topic: 2, type: 'N' },
    { word: 'kinship', meaning: ['quan hệ họ hàng'], synonyms: '', topic: 2, type: 'N' },

    //adj: 1-39:
    { word: 'diverse', meaning: ['đa dạng'], synonyms: 'varied, different', topic: 2, type: 'ADJ' },
    { word: 'tolerant', meaning: ['khoan dung'], synonyms: 'accepting, open-minded', topic: 2, type: 'ADJ' },
    { word: 'respectful', meaning: ['biết tôn trọng, lễ phép'], synonyms: 'polite, courteous', topic: 2, type: 'ADJ' },
    { word: 'multicultural', meaning: ['đa văn hóa'], synonyms: 'diverse, pluralistic', topic: 2, type: 'ADJ' },
    { word: 'inclusive', meaning: ['bao gồm, bao hàm'], synonyms: 'comprehensive, embracing', topic: 2, type: 'ADJ' },
    { word: 'religious', meaning: ['thuộc tôn giáo'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'ethnic', meaning: ['thuộc dân tộc'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'open-minded', meaning: ['rộng lượng, cởi mở'], synonyms: 'receptive, tolerant', topic: 2, type: 'ADJ' },
    { word: 'biased', meaning: ['có thành kiến'], synonyms: 'prejudiced, one-sided', topic: 2, type: 'ADJ' },
    { word: 'prejudiced', meaning: ['có thành kiến'], synonyms: 'biased, discriminatory', topic: 2, type: 'ADJ' },
    { word: 'misunderstood', meaning: ['bị hiểu lầm'], synonyms: 'misinterpreted, misjudged', topic: 2, type: 'ADJ' },
    { word: 'welcoming', meaning: ['thân thiện, hoan nghênh'], synonyms: 'friendly, inviting', topic: 2, type: 'ADJ' },
    { word: 'discriminatory', meaning: ['phân biệt đối xử'], synonyms: 'biased, prejudiced', topic: 2, type: 'ADJ' },
    { word: 'unique', meaning: ['độc nhất'], synonyms: 'singular, distinctive', topic: 2, type: 'ADJ' },
    { word: 'common', meaning: ['phổ biến'], synonyms: 'popular, pervasive, ubiquitous', topic: 2, type: 'ADJ' },
    { word: 'generational', meaning: ['thuộc về thế hệ'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'cross-cultural', meaning: ['đa văn hóa'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'linguistic', meaning: ['thuộc ngôn ngữ'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'customary', meaning: ['theo phong tục'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'indigenous', meaning: ['bản địa'], synonyms: 'native', topic: 2, type: 'ADJ' },
    { word: 'communal', meaning: ['chung, cộng đồng'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'foreign', meaning: ['nước ngoài'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'intolerant', meaning: ['không khoan dung'], synonyms: 'narrow-minded, prejudiced', topic: 2, type: 'ADJ' },
    { word: 'homogeneous', meaning: ['đồng nhất'], synonyms: 'uniform, consistent', topic: 2, type: 'ADJ' },
    { word: 'contemporary', meaning: ['đương đại'], synonyms: 'modern, current', topic: 2, type: 'ADJ' },
    { word: 'conservative', meaning: ['bảo thủ'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'patriotic', meaning: ['yêu nước'], synonyms: 'nationalistic, altruistic', topic: 2, type: 'ADJ' },
    { word: 'receptive', meaning: ['dễ tiếp thu'], synonyms: 'open (to), responsive (to)', topic: 2, type: 'ADJ' },
    { word: 'sensitive', meaning: ['nhạy cảm'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'respectable', meaning: ['đáng kính'], synonyms: 'honorable, reputable', topic: 2, type: 'ADJ' },
    { word: 'harmonious', meaning: ['hòa hợp'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'isolated', meaning: ['bị cô lập'], synonyms: 'detached (from), secluded', topic: 2, type: 'ADJ' },
    { word: 'reserved', meaning: ['dè dặt, hướng nội'], synonyms: 'introverted', topic: 2, type: 'ADJ' },
    { word: 'expressive', meaning: ['mang tính biểu cảm'], synonyms: 'demonstrative', topic: 2, type: 'ADJ' },
    { word: 'observant', meaning: ['tinh ý'], synonyms: 'attentive, perceptive', topic: 2, type: 'ADJ' },
    { word: 'flexible', meaning: ['linh hoạt'], synonyms: 'adaptable, versatile', topic: 2, type: 'ADJ' },
    { word: 'faith-based', meaning: ['dựa trên đức tin'], synonyms: 'religious, spiritual', topic: 2, type: 'ADJ' },
    { word: 'connected', meaning: ['có liên quan tới'], synonyms: 'linked (to), related to, associated with', topic: 2, type: 'ADJ' },
    { word: 'recognized', meaning: ['được công nhận'], synonyms: 'acknowledged, accepted', topic: 2, type: 'ADJ' },

    //PV: 1-45
    { word: 'adapt to', meaning: ['thích nghi với'], synonyms: 'adjust to, get used to', topic: 2, type: 'PV' },
    { word: 'find out about', meaning: ['tìm hiểu về'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'come from', meaning: ['đến từ'], synonyms: 'originate from, stem from', topic: 2, type: 'PV' },
    { word: 'open up about', meaning: ['mở lòng về'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'keep up with', meaning: ['theo kịp'], synonyms: 'keep pace with, catch up with, stay updated with', topic: 2, type: 'PV' },
    { word: 'look up to', meaning: ['kính trọng'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'come together', meaning: ['đoàn kết'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'take on', meaning: ['đảm nhận'], synonyms: 'undertake', topic: 2, type: 'PV' },
    { word: 'settle into', meaning: ['hòa nhập vào'], synonyms: 'adjust to, get used to', topic: 2, type: 'PV' },
    { word: 'speak up for', meaning: ['lên tiếng bảo vệ'], synonyms: 'advocate for, defend', topic: 2, type: 'PV' },
    { word: 'get over', meaning: ['vượt qua'], synonyms: 'overcome, conquer, recover from', topic: 2, type: 'PV' },
    { word: 'go through', meaning: ['trải qua'], synonyms: 'experience, endure', topic: 2, type: 'PV' },
    { word: 'catch on', meaning: ['trở nên phổ biến', 'hiểu ra'], synonyms: 'become popular, understand, grasp', topic: 2, type: 'PV' },
    { word: 'pass down', meaning: ['truyền lại'], synonyms: 'hand down', topic: 2, type: 'PV' },
    { word: 'turn to', meaning: ['tìm đến'], synonyms: 'resort to, rely on, fall back on', topic: 2, type: 'PV' },
    { word: 'bring in', meaning: ['giới thiệu, ban hành'], synonyms: 'introduce, enact, implement', topic: 2, type: 'PV' },
    { word: 'take over', meaning: ['tiếp quản'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'go against', meaning: ['chống lại'], synonyms: 'oppose, defy', topic: 2, type: 'PV' },
    { word: 'put off', meaning: ['trì hoãn', 'làm ai chán ghét'], synonyms: 'delay, postpone, put sth on hold', topic: 2, type: 'PV' },
    { word: 'find out', meaning: ['khám phá'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'come up with', meaning: ['nghĩ ra'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'step into', meaning: ['bước vào'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'reach out to', meaning: ['tiếp cận'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'back up', meaning: ['hỗ trợ', 'sao lưu'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'go along with', meaning: ['đồng thuận, hòa thuận với'], synonyms: 'get on with, be/keep on good terms with', topic: 2, type: 'PV' },
    { word: 'make up', meaning: ['trang điểm', 'bịa ra', 'chiếm', 'làm hòa', 'bù đắp'], synonyms: 'invent, fabricate, reconcile, compensate', topic: 2, type: 'PV' },
    { word: 'work out', meaning: ['tập thể hình', 'có hiệu quả', 'giải quyết'], synonyms: 'be effective, figure out', topic: 2, type: 'PV' },
    { word: 'let go of', meaning: ['buông bỏ'], synonyms: 'release, give up', topic: 2, type: 'PV' },
    { word: 'hold back', meaning: ['kiềm nén'], synonyms: 'restrain, control', topic: 2, type: 'PV' },
    { word: 'fall behind', meaning: ['tụt lại'], synonyms: 'lag behind', topic: 2, type: 'PV' },
    { word: 'pick up', meaning: ['nhặt', 'đón', 'mắc bệnh', 'học được'], synonyms: 'come down with, learn, acquire', topic: 2, type: 'PV' },
    { word: 'turn away from', meaning: ['quay lưng'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'get exposed to', meaning: ['tiếp xúc với'], synonyms: 'be exposed to, encounter', topic: 2, type: 'PV' },
    { word: 'mix in', meaning: ['hòa nhập'], synonyms: 'blend in, fit in, integrate', topic: 2, type: 'PV' },
    { word: 'take part in', meaning: ['tham gia'], synonyms: 'participate in, engage in', topic: 2, type: 'PV' },
    { word: 'lead to', meaning: ['dẫn đến'], synonyms: 'result in, cause, bring about', topic: 2, type: 'PV' },
    { word: 'pass knowledge to', meaning: ['truyền đạt kiến thức'], synonyms: 'transmit knowledge to, disseminate knowledge to', topic: 2, type: 'PV' },
    { word: 'refer to', meaning: ['đề cập đến'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'stay rooted in', meaning: ['giữ vững', 'gắn bó'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'engage with', meaning: ['giao tiếp với', 'tương tác với'], synonyms: 'interact with, communicate with', topic: 2, type: 'PV' },
    { word: 'blend ... with ...', meaning: ['hòa trộn với'], synonyms: 'mix with, combine with', topic: 2, type: 'PV' },
    { word: 'ward off', meaning: ['đẩy lùi'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'take in', meaning: ['chiêm ngưỡng', 'lừa gạt', 'tiếp thu', 'hiểu'], synonyms: 'admire, deceive, absorb, understand', topic: 2, type: 'PV' },
    { word: 'look after', meaning: ['chăm sóc'], synonyms: 'take care of, care for', topic: 2, type: 'PV' },
    { word: 'serve as', meaning: ['đóng vai trò'], synonyms: 'function as, act as', topic: 2, type: 'V' },

];
