const words = [
    // CHU DE 1
    // V:1-27:
    { word: 'overcome', meaning: ['vượt qua'], synonyms: 'get through', topic: 1, type: 'V' },
    { word: 'discover', meaning: ['khám phá'], synonyms: 'find out, explore', topic: 1, type: 'V' },
    { word: 'reflect', meaning: ['phản chiếu'], synonyms: 'mirror, show', topic: 1, type: 'V' },
    { word: 'struggle', meaning: ['vật lộn'], synonyms: 'fight, battle', topic: 1, type: 'V' },
    { word: 'inspire', meaning: ['truyền cảm hứng'], synonyms: 'motivate, encourage', topic: 1, type: 'V' },
    { word: 'motivate', meaning: ['tạo động lực'], synonyms: 'encourage, drive', topic: 1, type: 'V' },
    { word: 'accomplish', meaning: ['hoàn thành'], synonyms: 'achieve, complete', topic: 1, type: 'V' },
    { word: 'transform', meaning: ['biến đổi'], synonyms: 'change, convert', topic: 1, type: 'V' },
    { word: 'stimulate', meaning: ['kích thích'], synonyms: 'encourage, boost', topic: 1, type: 'V' },
    { word: 'confront', meaning: ['đối mặt'], synonyms: 'face, encounter', topic: 1, type: 'V' },
    { word: 'sacrifice', meaning: ['hy sinh'], synonyms: 'give up', topic: 1, type: 'V' },
    { word: 'challenge', meaning: ['thách thức'], synonyms: 'defy, question', topic: 1, type: 'V' },
    { word: 'pursue', meaning: ['theo đuổi'], synonyms: 'follow, seek', topic: 1, type: 'V' },
    { word: 'recognize', meaning: ['công nhận'], synonyms: 'acknowledge', topic: 1, type: 'V' },
    { word: 'adapt', meaning: ['thích nghi với'], synonyms: 'adjust', topic: 1, type: 'V' },
    { word: 'cope with', meaning: ['đối phó với'], synonyms: 'deal with', topic: 1, type: 'V' },
    { word: 'manage', meaning: ['quản lý'], synonyms: 'control, handle', topic: 1, type: 'V' },
    { word: 'strive for', meaning: ['phấn đấu cho'], synonyms: 'aim for, try hard', topic: 1, type: 'V' },
    { word: 'rebuild', meaning: ['xây dựng lại'], synonyms: 'reconstruct, restore', topic: 1, type: 'V' },
    { word: 'consolidate', meaning: ['củng cố'], synonyms: 'strengthen, build up', topic: 1, type: 'V' },
    { word: 'demonstrate', meaning: ['chứng minh'], synonyms: '', topic: 1, type: 'V' },
    { word: 'appreciate', meaning: ['trân trọng', 'đánh giá cao'], synonyms: '', topic: 1, type: 'V' },
    { word: 'survive', meaning: ['sống sót', 'tồn tại'], synonyms: 'endure, outlive', topic: 1, type: 'V' },
    { word: 'attempt', meaning: ['cố gắng', 'nỗ lực'], synonyms: '', topic: 1, type: 'V' },
    { word: 'represent', meaning: ['đại diện cho', 'biểu tượng cho'], synonyms: 'stand for, symbolize', topic: 1, type: 'V' },
    { word: 'evaluate', meaning: ['đánh giá'], synonyms: 'assess, judge, appraise', topic: 1, type: 'V' },
    { word: 'define', meaning: ['định nghĩa'], synonyms: 'describe, explain', topic: 1, type: 'V' },

    // N:1-30:
    { word: 'struggle', meaning: 'sự đấu tranh', synonyms: '', topic: 1, type: 'N' },
    { word: 'ambition', meaning: 'tham vọng', synonyms: '', topic: 1, type: 'N' },
    { word: 'challenge', meaning: 'thử thách, thách thức', synonyms: 'difficulty, obstacle, impediment', topic: 1, type: 'N' },
    { word: 'turning point', meaning: 'bước ngoặt', synonyms: 'breakthrough, milestone', topic: 1, type: 'N' },
    { word: 'inspiration', meaning: 'nguồn cảm hứng', synonyms: 'motivation, encouragement', topic: 1, type: 'N' },
    { word: 'background', meaning: 'nền tảng (xuất thân)', synonyms: 'origin, upbringing', topic: 1, type: 'N' },
    { word: 'motivation', meaning: 'động lực', synonyms: 'drive, incentive', topic: 1, type: 'N' },
    { word: 'reputation', meaning: 'danh tiếng', synonyms: 'fame, status', topic: 1, type: 'N' },
    { word: 'identity', meaning: 'bản sắc', synonyms: '', topic: 1, type: 'N' },
    { word: 'disappointment', meaning: 'sự thất vọng', synonyms: '', topic: 1, type: 'N' },
    { word: 'achievement', meaning: 'thành tựu', synonyms: 'accomplishment, success', topic: 1, type: 'N' },
    { word: 'encouragement', meaning: 'sự khích lệ', synonyms: '', topic: 1, type: 'N' },
    { word: 'destiny', meaning: 'định mệnh', synonyms: '', topic: 1, type: 'N' },
    { word: 'obstacle', meaning: 'chướng ngại', synonyms: 'barrier, hindrance, impediment', topic: 1, type: 'N' },
    { word: 'emotion', meaning: 'cảm xúc', synonyms: '', topic: 1, type: 'N' },
    { word: 'conflict', meaning: 'sự xung đột', synonyms: 'clash, disagreement', topic: 1, type: 'N' },
    { word: 'strength', meaning: 'sức mạnh', synonyms: '', topic: 1, type: 'N' },
    { word: 'honesty', meaning: 'sự trung thực', synonyms: 'integrity, truthfulness', topic: 1, type: 'N' },
    { word: 'perseverance', meaning: 'sự kiên trì', synonyms: 'persistence, determination', topic: 1, type: 'N' },
    { word: 'determination', meaning: 'sự quyết tâm', synonyms: 'tenacity, perseverance', topic: 1, type: 'N' },
    { word: 'self-confidence', meaning: 'sự tự tin', synonyms: '', topic: 1, type: 'N' },
    { word: 'forgiveness', meaning: 'sự tha thứ', synonyms: '', topic: 1, type: 'N' },
    { word: 'legacy', meaning: 'di sản', synonyms: '', topic: 1, type: 'N' },
    { word: 'purpose', meaning: 'mục đích', synonyms: '', topic: 1, type: 'N' },
    { word: 'kindness', meaning: 'lòng tốt', synonyms: 'compassion, generosity', topic: 1, type: 'N' },
    { word: 'responsibility', meaning: 'trách nhiệm', synonyms: '', topic: 1, type: 'N' },
    { word: 'empathy', meaning: 'sự đồng cảm', synonyms: 'compassion, understanding', topic: 1, type: 'N' },
    { word: 'vision', meaning: 'tầm nhìn', synonyms: 'foresight, outlook', topic: 1, type: 'N' },
    { word: 'belief', meaning: 'niềm tin', synonyms: 'conviction, faith', topic: 1, type: 'N' },
    { word: 'passion', meaning: 'đam mê', synonyms: 'enthusiasm, fervor', topic: 1, type: 'N' },
    // ADJ:1-10:
    { word: 'determined', meaning: 'quyết tâm', synonyms: 'resolute, steadfast', topic: 1, type: 'ADJ' },
    { word: 'inspirational', meaning: 'truyền cảm hứng', synonyms: 'motivating, uplifting', topic: 1, type: 'ADJ' },
    { word: 'memorable', meaning: 'đáng nhớ', synonyms: 'unforgettable, eventful', topic: 1, type: 'ADJ' },
    { word: 'successful', meaning: 'thành công', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'courageous', meaning: 'dũng cảm', synonyms: 'brave, valiant', topic: 1, type: 'ADJ' },
    { word: 'emotional', meaning: 'cảm xúc', synonyms: 'sentimental', topic: 1, type: 'ADJ' },
    { word: 'motivated', meaning: 'có động lực', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'resilient', meaning: 'kiên cường', synonyms: 'tough, adaptable', topic: 1, type: 'ADJ' },
    { word: 'hopeful', meaning: 'đầy hy vọng', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'remarkable', meaning: 'đáng chú ý', synonyms: 'extraordinary, notable, exceptional, outstanding', topic: 1, type: 'ADJ' },

    // ADJ:11-30:
    { word: 'passionate', meaning: 'đam mê', synonyms: 'enthusiastic, fervent', topic: 1, type: 'ADJ' },
    { word: 'independent', meaning: 'độc lập', synonyms: 'self-reliant, autonomous', topic: 1, type: 'ADJ' },
    { word: 'thoughtful', meaning: 'chu đáo', synonyms: 'considerate', topic: 1, type: 'ADJ' },
    { word: 'loyal', meaning: 'trung thành', synonyms: 'faithful, devoted', topic: 1, type: 'ADJ' },
    { word: 'confident', meaning: 'tự tin', synonyms: 'self-assured, assured', topic: 1, type: 'ADJ' },
    { word: 'grateful', meaning: 'biết ơn', synonyms: 'thankful, appreciative', topic: 1, type: 'ADJ' },
    { word: 'faithful', meaning: 'trung thực', synonyms: 'loyal, devoted', topic: 1, type: 'ADJ' },
    { word: 'influential', meaning: 'có ảnh hưởng', synonyms: 'powerful, persuasive', topic: 1, type: 'ADJ' },
    { word: 'supportive', meaning: 'ủng hộ', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'compassionate', meaning: 'nhân ái', synonyms: 'empathetic, kind-hearted', topic: 1, type: 'ADJ' },
    { word: 'decisive', meaning: 'quyết đoán', synonyms: 'resolute, determined', topic: 1, type: 'ADJ' },
    { word: 'reflective', meaning: 'suy tư', synonyms: 'contemplative, thoughtful', topic: 1, type: 'ADJ' },
    { word: 'generous', meaning: 'hào phóng', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'sensitive', meaning: 'nhạy cảm', synonyms: '', topic: 1, type: 'ADJ' },
    { word: 'respectful', meaning: ['tôn trọng', 'lễ phép'], synonyms: 'courteous, polite', topic: 1, type: 'ADJ' },
    { word: 'self-aware', meaning: 'tự nhận thức', synonyms: 'introspective, self-conscious', topic: 1, type: 'ADJ' },
    { word: 'rational', meaning: 'lý trí', synonyms: 'logical, reasonable, sensible', topic: 1, type: 'ADJ' },
    { word: 'gentle', meaning: 'dịu dàng', synonyms: 'kind, tender', topic: 1, type: 'ADJ' },
    { word: 'optimistic', meaning: 'lạc quan', synonyms: 'hopeful, positive', topic: 1, type: 'ADJ' },
    { word: 'fearless', meaning: 'không sợ hãi', synonyms: 'brave, bold', topic: 1, type: 'ADJ' },

    // PV:1-45:
    { word: 'earn a prize', meaning: 'giành được giải thưởng', synonyms: '', topic: 1, type: 'PV' },
    { word: 'take on', meaning: 'đảm nhận (trách nhiệm, nhiệm vụ)', synonyms: '', topic: 1, type: 'PV' },
    { word: 'pursue your dream', meaning: 'theo đuổi ước mơ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'follow in one’s footsteps', meaning: 'theo bước ai đó', synonyms: '', topic: 1, type: 'PV' },
    { word: 'strive for', meaning: 'phấn đấu vì', synonyms: '', topic: 1, type: 'PV' },
    { word: 'deal with', meaning: 'giải quyết', synonyms: 'cope with, handle, resolve, address, combat', topic: 1, type: 'PV' },
    { word: 'carry on', meaning: 'tiếp tục', synonyms: 'continue, go on, press on, press ahead', topic: 1, type: 'PV' },
    { word: 'find out', meaning: 'phát hiện ra', synonyms: 'discover, figure out, work out', topic: 1, type: 'PV' },
    { word: 'gain knowledge', meaning: 'tích lũy kiến thức', synonyms: 'acquire knowledge, absorb knowledge', topic: 1, type: 'PV' },
    { word: 'seek support', meaning: 'tìm kiếm sự hỗ trợ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'face challenge', meaning: 'đối mặt với thử thách', synonyms: 'confront, encounter', topic: 1, type: 'PV' },
    { word: 'gain recognition', meaning: 'đạt được sự công nhận', synonyms: '', topic: 1, type: 'PV' },
    { word: 'bring about', meaning: 'gây ra', synonyms: 'result in, lead to, give rise to, contribute to, allow for', topic: 1, type: 'PV' },
    { word: 'chase your passion', meaning: 'theo đuổi đam mê', synonyms: '', topic: 1, type: 'PV' },
    { word: 'make something a reality', meaning: 'biến điều gì thành hiện thực', synonyms: '', topic: 1, type: 'PV' },
    { word: 'grow up', meaning: 'lớn lên, trưởng thành', synonyms: '', topic: 1, type: 'PV' },
    { word: 'rise to stardom', meaning: 'trở nên nổi tiếng', synonyms: '', topic: 1, type: 'PV' },
    { word: 'contribute to', meaning: 'đóng góp vào', synonyms: 'add to, be part of', topic: 1, type: 'PV' },
    { word: 'set up', meaning: 'thiết lập', synonyms: 'establish, found', topic: 1, type: 'PV' },
    { word: 'look up', meaning: ['tra cứu', 'ngưỡng mộ'], synonyms: '', topic: 1, type: 'PV' },
    { word: 'face your fear', meaning: 'đối mặt với nỗi sợ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'push yourself beyond your limit', meaning: 'vượt qua giới hạn', synonyms: 'exceed your limit, step out of your comfort zone', topic: 1, type: 'PV' },
    { word: 'play an important role in', meaning: 'đóng vai trò quan trọng', synonyms: 'be instrumental in', topic: 1, type: 'PV' },
    { word: 'take a chance on', meaning: 'đánh liều với', synonyms: 'risk Ving, gamble on, take a risk', topic: 1, type: 'PV' },
    { word: 'make a difference', meaning: 'tạo ra sự khác biệt', synonyms: 'impact, change for the better', topic: 1, type: 'PV' },
    { word: 'face up to', meaning: 'đối mặt với', synonyms: 'confront with', topic: 1, type: 'PV' },
    { word: 'pick yourself up', meaning: 'đứng dậy', synonyms: 'recover from, bounce back, regain composure', topic: 1, type: 'PV' },
    { word: 'push through', meaning: 'vượt qua', synonyms: 'persevere, persist, overcome', topic: 1, type: 'PV' },
    { word: 'break through', meaning: 'đột phá', synonyms: '', topic: 1, type: 'PV' },
    { word: 'stand out', meaning: 'nổi bật', synonyms: '', topic: 1, type: 'PV' },
    { word: 'get over', meaning: 'vượt qua', synonyms: 'recover, overcome, conquer', topic: 1, type: 'PV' },
    { word: 'turn back', meaning: 'quay lại', synonyms: '', topic: 1, type: 'PV' },
    { word: 'catch up with', meaning: 'bắt kịp', synonyms: 'keep up with, keep pace with', topic: 1, type: 'PV' },
    { word: 'get through', meaning: 'vượt qua', synonyms: 'endure, survive, complete', topic: 1, type: 'PV' },
    { word: 'look out for', meaning: 'trông chừng', synonyms: 'watch out for', topic: 1, type: 'PV' },
    { word: 'come up with', meaning: 'nghĩ ra', synonyms: 'devise, invent, formulate', topic: 1, type: 'PV' },
    { word: 'put up with', meaning: 'chịu đựng', synonyms: 'tolerate, endure, bear', topic: 1, type: 'PV' },
    { word: 'fit in', meaning: 'hòa nhập', synonyms: '', topic: 1, type: 'PV' },
    { word: 'stand by', meaning: 'ủng hộ', synonyms: '', topic: 1, type: 'PV' },
    { word: 'let go of', meaning: 'buông bỏ', synonyms: 'relinquish, abandon', topic: 1, type: 'PV' },
    { word: 'tear up', meaning: 'xúc động', synonyms: '', topic: 1, type: 'PV' },
    { word: 'back away', meaning: 'lùi lại', synonyms: 'retreat, withdraw (from), step back (from)', topic: 1, type: 'PV' },
    { word: 'run away from', meaning: 'chạy trốn', synonyms: '', topic: 1, type: 'PV' },
    { word: 'stick with', meaning: 'gắn bó với', synonyms: 'stick to sth: tuân thủ (luật/quy tắc)', topic: 1, type: 'PV' },
    { word: 'look after', meaning: 'chăm sóc', synonyms: 'care for, attend to', topic: 1, type: 'PV' },


    // CHU DE 2
    // Verb: 1-35
    { word: 'integrate', meaning: ['hòa nhập', 'hội nhập', 'tích hợp', 'kết hợp'], synonyms: 'incorporate', topic: 2, type: 'V' },
    { word: 'assimilate', meaning: 'đồng hóa', synonyms: '', topic: 2, type: 'V' },
    { word: 'embrace', meaning: 'đón nhận', synonyms: 'accept, welcome, come to terms with', topic: 2, type: 'V' },
    { word: 'recognize', meaning: 'công nhận', synonyms: 'acknowledge', topic: 2, type: 'V' },
    { word: 'preserve', meaning: 'bảo tồn', synonyms: '', topic: 2, type: 'V' },
    { word: 'celebrate', meaning: 'tôn vinh', synonyms: 'honor, observe', topic: 2, type: 'V' },
    { word: 'overcome', meaning: 'vượt qua', synonyms: 'conquer, defeat', topic: 2, type: 'V' },
    { word: 'encounter', meaning: 'bắt gặp (ai/cái gì), gặp (vấn đề)', synonyms: 'run into, come up against', topic: 2, type: 'V' },
    { word: 'represent', meaning: 'đại diện', synonyms: 'stand for, symbolize', topic: 2, type: 'V' },
    { word: 'express', meaning: 'bày tỏ', synonyms: 'convey, communicate, deliver', topic: 2, type: 'V' },

    { word: 'maintain', meaning: 'duy trì', synonyms: 'preserve, sustain', topic: 2, type: 'V' },
    { word: 'bridge', meaning: 'thu hẹp (khoảng cách)', synonyms: 'narrow, reduce the gap', topic: 2, type: 'V' },
    { word: 'misunderstand', meaning: 'hiểu sai', synonyms: 'misinterpret', topic: 2, type: 'V' },
    { word: 'unite', meaning: 'đoàn kết', synonyms: '', topic: 2, type: 'V' },
    { word: 'interact', meaning: 'tương tác', synonyms: '', topic: 2, type: 'V' },
    { word: 'discriminate', meaning: ['phân biệt đối xử', 'phân biệt (cái gì với cái gì)'], synonyms: 'differentiate, distinguish', topic: 2, type: 'V' },
    { word: 'highlight', meaning: 'nhấn mạnh', synonyms: 'emphasize, stress, underscore', topic: 2, type: 'V' },
    { word: 'emphasize', meaning: 'nhấn mạnh', synonyms: 'highlight, underline', topic: 2, type: 'V' },
    { word: 'promote', meaning: 'thúc đẩy', synonyms: 'encourage, foster, nurture', topic: 2, type: 'V' },
    { word: 'undermine', meaning: 'làm suy yếu', synonyms: 'weaken, sabotage', topic: 2, type: 'V' },

    { word: 'participate', meaning: 'tham gia vào', synonyms: 'join, engage in, partake in, take part in, be/get involved in, be part of', topic: 2, type: 'V' },
    { word: 'generalize', meaning: 'khái quát hóa', synonyms: '', topic: 2, type: 'V' },
    { word: 'encourage', meaning: 'khuyến khích', synonyms: 'inspire, motivate', topic: 2, type: 'V' },
    { word: 'observe', meaning: ['quan sát', 'tuân thủ'], synonyms: 'watch, notice, follow, comply with', topic: 2, type: 'V' },
    { word: 'compound', meaning: 'làm phức tạp', synonyms: 'worsen, exacerbate, aggravate', topic: 2, type: 'V' },
    { word: 'reinforce', meaning: 'củng cố', synonyms: 'strengthen, support', topic: 2, type: 'V' },
    { word: 'offend', meaning: 'xúc phạm', synonyms: '', topic: 2, type: 'V' },
    { word: 'conform', meaning: 'tuân theo', synonyms: 'follow, obey, observe, adhere to, abide by, stick to, comply with', topic: 2, type: 'V' },
    { word: 'reject', meaning: 'từ chối', synonyms: 'refuse, decline', topic: 2, type: 'V' },
    { word: 'interpret', meaning: 'diễn giải', synonyms: 'explain, translate', topic: 2, type: 'V' },

    { word: 'adapt', meaning: ['thích nghi'], synonyms: 'adjust, modify', topic: 2, type: 'V' },
    { word: 'transfer', meaning: ['chuyển giao'], synonyms: '', topic: 2, type: 'V' },
    { word: 'navigate', meaning: ['điều hướng'], synonyms: 'steer, manage', topic: 2, type: 'V' },
    { word: 'overlook', meaning: ['bỏ qua'], synonyms: '', topic: 2, type: 'V' },
    { word: 'exclude', meaning: ['loại trừ'], synonyms: 'leave out, eliminate', topic: 2, type: 'V' },
    //noun : 1-43
    { word: 'ethnicity', meaning: ['dân tộc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'heritage', meaning: ['di sản'], synonyms: '', topic: 2, type: 'N' },
    { word: 'assimilation', meaning: ['sự đồng hóa'], synonyms: '', topic: 2, type: 'N' },
    { word: 'integration', meaning: ['sự hòa nhập'], synonyms: '', topic: 2, type: 'N' },
    { word: 'tradition', meaning: ['truyền thống'], synonyms: '', topic: 2, type: 'N' },
    { word: 'custom', meaning: ['phong tục'], synonyms: '', topic: 2, type: 'N' },
    { word: 'multiculturalism', meaning: ['sự đa văn hóa'], synonyms: 'cultural diversity, pluralism', topic: 2, type: 'N' },
    { word: 'identity', meaning: ['bản sắc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'background', meaning: ['hoàn cảnh'], synonyms: '', topic: 2, type: 'N' },
    { word: 'norm', meaning: ['chuẩn mực'], synonyms: '', topic: 2, type: 'N' },
    { word: 'stereotype', meaning: ['định kiến'], synonyms: '', topic: 2, type: 'N' },
    { word: 'prejudice', meaning: ['thành kiến'], synonyms: 'bias, discrimination', topic: 2, type: 'N' },
    { word: 'discrimination', meaning: ['sự phân biệt đối xử'], synonyms: 'prejudice, unfairness', topic: 2, type: 'N' },
    { word: 'tolerance', meaning: ['sự khoan dung'], synonyms: 'acceptance, open-mindedness', topic: 2, type: 'N' },
    { word: 'ritual', meaning: ['nghi lễ'], synonyms: '', topic: 2, type: 'N' },
    { word: 'minority', meaning: ['thiểu số'], synonyms: '', topic: 2, type: 'N' },
    { word: 'majority', meaning: ['đa số'], synonyms: '', topic: 2, type: 'N' },
    { word: 'ethnocentrism', meaning: ['chủ nghĩa dân tộc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'barrier', meaning: ['rào cản'], synonyms: 'obstacle, hurdle, impediment', topic: 2, type: 'N' },
    { word: 'diversity', meaning: ['sự đa dạng'], synonyms: 'variety', topic: 2, type: 'N' },
    { word: 'globalization', meaning: ['toàn cầu hóa'], synonyms: '', topic: 2, type: 'N' },
    { word: 'hospitality', meaning: ['lòng hiếu khách'], synonyms: '', topic: 2, type: 'N' },
    { word: 'race', meaning: ['chủng tộc'], synonyms: '', topic: 2, type: 'N' },
    { word: 'religion', meaning: ['tôn giáo'], synonyms: '', topic: 2, type: 'N' },
    { word: 'perspective', meaning: ['quan điểm'], synonyms: 'opinion, viewpoint, outlook, point of view', topic: 2, type: 'N' },
    { word: 'cultural shock', meaning: ['sốc văn hóa'], synonyms: '', topic: 2, type: 'N' },
    { word: 'unity', meaning: ['sự đoàn kết'], synonyms: 'solidarity, harmony', topic: 2, type: 'N' },
    { word: 'interaction', meaning: ['sự tương tác'], synonyms: '', topic: 2, type: 'N' },
    { word: 'community', meaning: ['cộng đồng'], synonyms: '', topic: 2, type: 'N' },
    { word: 'misunderstanding', meaning: ['sự hiểu nhầm'], synonyms: '', topic: 2, type: 'N' },
    { word: 'symbolism', meaning: ['biểu tượng học'], synonyms: '', topic: 2, type: 'N' },
    { word: 'patriotism', meaning: ['chủ nghĩa yêu nước'], synonyms: 'nationalism, altruism', topic: 2, type: 'N' },
    { word: 'xenophobia', meaning: ['sự kỳ thị người nước ngoài'], synonyms: '', topic: 2, type: 'N' },
    { word: 'respect', meaning: ['sự tôn trọng'], synonyms: '', topic: 2, type: 'N' },
    { word: 'acceptance', meaning: ['sự chấp nhận'], synonyms: 'approval, recognition', topic: 2, type: 'N' },
    { word: 'representation', meaning: ['sự đại diện'], synonyms: '', topic: 2, type: 'N' },
    { word: 'inclusion', meaning: ['sự bao gồm'], synonyms: '', topic: 2, type: 'N' },
    { word: 'coexistence', meaning: ['sự cùng tồn tại'], synonyms: '', topic: 2, type: 'N' },
    { word: 'nationality', meaning: ['quốc tịch'], synonyms: '', topic: 2, type: 'N' },
    { word: 'belonging', meaning: ['sự thuộc về'], synonyms: '', topic: 2, type: 'N' },
    { word: 'civilization', meaning: ['nền văn minh'], synonyms: '', topic: 2, type: 'N' },
    { word: 'convention', meaning: ['hội nghị'], synonyms: '', topic: 2, type: 'N' },
    { word: 'kinship', meaning: ['quan hệ họ hàng'], synonyms: '', topic: 2, type: 'N' },

    //adj: 1-39:
    { word: 'diverse', meaning: ['đa dạng'], synonyms: 'varied, different', topic: 2, type: 'ADJ' },
    { word: 'tolerant', meaning: ['khoan dung'], synonyms: 'accepting, open-minded', topic: 2, type: 'ADJ' },
    { word: 'respectful', meaning: ['biết tôn trọng, lễ phép'], synonyms: 'polite, courteous', topic: 2, type: 'ADJ' },
    { word: 'multicultural', meaning: ['đa văn hóa'], synonyms: 'diverse, pluralistic', topic: 2, type: 'ADJ' },
    { word: 'inclusive', meaning: ['bao gồm, bao hàm'], synonyms: 'comprehensive, embracing', topic: 2, type: 'ADJ' },
    { word: 'religious', meaning: ['thuộc tôn giáo'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'ethnic', meaning: ['thuộc dân tộc'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'open-minded', meaning: ['rộng lượng, cởi mở'], synonyms: 'receptive, tolerant', topic: 2, type: 'ADJ' },
    { word: 'biased', meaning: ['có thành kiến'], synonyms: 'prejudiced, one-sided', topic: 2, type: 'ADJ' },
    { word: 'prejudiced', meaning: ['có thành kiến'], synonyms: 'biased, discriminatory', topic: 2, type: 'ADJ' },
    { word: 'misunderstood', meaning: ['bị hiểu lầm'], synonyms: 'misinterpreted, misjudged', topic: 2, type: 'ADJ' },
    { word: 'welcoming', meaning: ['thân thiện, hoan nghênh'], synonyms: 'friendly, inviting', topic: 2, type: 'ADJ' },
    { word: 'discriminatory', meaning: ['phân biệt đối xử'], synonyms: 'biased, prejudiced', topic: 2, type: 'ADJ' },
    { word: 'unique', meaning: ['độc nhất'], synonyms: 'singular, distinctive', topic: 2, type: 'ADJ' },
    { word: 'common', meaning: ['phổ biến'], synonyms: 'popular, pervasive, ubiquitous', topic: 2, type: 'ADJ' },
    { word: 'generational', meaning: ['thuộc về thế hệ'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'cross-cultural', meaning: ['đa văn hóa'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'linguistic', meaning: ['thuộc ngôn ngữ'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'customary', meaning: ['theo phong tục'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'indigenous', meaning: ['bản địa'], synonyms: 'native', topic: 2, type: 'ADJ' },
    { word: 'communal', meaning: ['chung, cộng đồng'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'foreign', meaning: ['nước ngoài'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'intolerant', meaning: ['không khoan dung'], synonyms: 'narrow-minded, prejudiced', topic: 2, type: 'ADJ' },
    { word: 'homogeneous', meaning: ['đồng nhất'], synonyms: 'uniform, consistent', topic: 2, type: 'ADJ' },
    { word: 'contemporary', meaning: ['đương đại'], synonyms: 'modern, current', topic: 2, type: 'ADJ' },
    { word: 'conservative', meaning: ['bảo thủ'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'patriotic', meaning: ['yêu nước'], synonyms: 'nationalistic, altruistic', topic: 2, type: 'ADJ' },
    { word: 'receptive', meaning: ['dễ tiếp thu'], synonyms: 'open (to), responsive (to)', topic: 2, type: 'ADJ' },
    { word: 'sensitive', meaning: ['nhạy cảm'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'respectable', meaning: ['đáng kính'], synonyms: 'honorable, reputable', topic: 2, type: 'ADJ' },
    { word: 'harmonious', meaning: ['hòa hợp'], synonyms: '', topic: 2, type: 'ADJ' },
    { word: 'isolated', meaning: ['bị cô lập'], synonyms: 'detached (from), secluded', topic: 2, type: 'ADJ' },
    { word: 'reserved', meaning: ['dè dặt, hướng nội'], synonyms: 'introverted', topic: 2, type: 'ADJ' },
    { word: 'expressive', meaning: ['mang tính biểu cảm'], synonyms: 'demonstrative', topic: 2, type: 'ADJ' },
    { word: 'observant', meaning: ['tinh ý'], synonyms: 'attentive, perceptive', topic: 2, type: 'ADJ' },
    { word: 'flexible', meaning: ['linh hoạt'], synonyms: 'adaptable, versatile', topic: 2, type: 'ADJ' },
    { word: 'faith-based', meaning: ['dựa trên đức tin'], synonyms: 'religious, spiritual', topic: 2, type: 'ADJ' },
    { word: 'connected', meaning: ['có liên quan tới'], synonyms: 'linked (to), related to, associated with', topic: 2, type: 'ADJ' },
    { word: 'recognized', meaning: ['được công nhận'], synonyms: 'acknowledged, accepted', topic: 2, type: 'ADJ' },

    //PV: 1-45
    { word: 'adapt to', meaning: ['thích nghi với'], synonyms: 'adjust to, get used to', topic: 2, type: 'PV' },
    { word: 'find out about', meaning: ['tìm hiểu về'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'come from', meaning: ['đến từ'], synonyms: 'originate from, stem from', topic: 2, type: 'PV' },
    { word: 'open up about', meaning: ['mở lòng về'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'keep up with', meaning: ['theo kịp'], synonyms: 'keep pace with, catch up with, stay updated with', topic: 2, type: 'PV' },
    { word: 'look up to', meaning: ['kính trọng'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'come together', meaning: ['đoàn kết'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'take on', meaning: ['đảm nhận'], synonyms: 'undertake', topic: 2, type: 'PV' },
    { word: 'settle into', meaning: ['hòa nhập vào'], synonyms: 'adjust to, get used to', topic: 2, type: 'PV' },
    { word: 'speak up for', meaning: ['lên tiếng bảo vệ'], synonyms: 'advocate for, defend', topic: 2, type: 'PV' },
    { word: 'get over', meaning: ['vượt qua'], synonyms: 'overcome, conquer, recover from', topic: 2, type: 'PV' },
    { word: 'go through', meaning: ['trải qua'], synonyms: 'experience, endure', topic: 2, type: 'PV' },
    { word: 'catch on', meaning: ['trở nên phổ biến', 'hiểu ra'], synonyms: 'become popular, understand, grasp', topic: 2, type: 'PV' },
    { word: 'pass down', meaning: ['truyền lại'], synonyms: 'hand down', topic: 2, type: 'PV' },
    { word: 'turn to', meaning: ['tìm đến'], synonyms: 'resort to, rely on, fall back on', topic: 2, type: 'PV' },
    { word: 'bring in', meaning: ['giới thiệu, ban hành'], synonyms: 'introduce, enact, implement', topic: 2, type: 'PV' },
    { word: 'take over', meaning: ['tiếp quản'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'go against', meaning: ['chống lại'], synonyms: 'oppose, defy', topic: 2, type: 'PV' },
    { word: 'put off', meaning: ['trì hoãn', 'làm ai chán ghét'], synonyms: 'delay, postpone, put sth on hold', topic: 2, type: 'PV' },
    { word: 'find out', meaning: ['khám phá'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'come up with', meaning: ['nghĩ ra'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'step into', meaning: ['bước vào'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'reach out to', meaning: ['tiếp cận'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'back up', meaning: ['hỗ trợ', 'sao lưu'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'go along with', meaning: ['đồng thuận, hòa thuận với'], synonyms: 'get on with, be/keep on good terms with', topic: 2, type: 'PV' },
    { word: 'make up', meaning: ['trang điểm', 'bịa ra', 'chiếm', 'làm hòa', 'bù đắp'], synonyms: 'invent, fabricate, reconcile, compensate', topic: 2, type: 'PV' },
    { word: 'work out', meaning: ['tập thể hình', 'có hiệu quả', 'giải quyết'], synonyms: 'be effective, figure out', topic: 2, type: 'PV' },
    { word: 'let go of', meaning: ['buông bỏ'], synonyms: 'release, give up', topic: 2, type: 'PV' },
    { word: 'hold back', meaning: ['kiềm nén'], synonyms: 'restrain, control', topic: 2, type: 'PV' },
    { word: 'fall behind', meaning: ['tụt lại'], synonyms: 'lag behind', topic: 2, type: 'PV' },
    { word: 'pick up', meaning: ['nhặt', 'đón', 'mắc bệnh', 'học được'], synonyms: 'come down with, learn, acquire', topic: 2, type: 'PV' },
    { word: 'turn away from', meaning: ['quay lưng'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'get exposed to', meaning: ['tiếp xúc với'], synonyms: 'be exposed to, encounter', topic: 2, type: 'PV' },
    { word: 'mix in', meaning: ['hòa nhập'], synonyms: 'blend in, fit in, integrate', topic: 2, type: 'PV' },
    { word: 'take part in', meaning: ['tham gia'], synonyms: 'participate in, engage in', topic: 2, type: 'PV' },
    { word: 'lead to', meaning: ['dẫn đến'], synonyms: 'result in, cause, bring about', topic: 2, type: 'PV' },
    { word: 'pass knowledge to', meaning: ['truyền đạt kiến thức'], synonyms: 'transmit knowledge to, disseminate knowledge to', topic: 2, type: 'PV' },
    { word: 'refer to', meaning: ['đề cập đến'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'stay rooted in', meaning: ['giữ vững', 'gắn bó'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'engage with', meaning: ['giao tiếp với', 'tương tác với'], synonyms: 'interact with, communicate with', topic: 2, type: 'PV' },
    { word: 'blend ... with ...', meaning: ['hòa trộn với'], synonyms: 'mix with, combine with', topic: 2, type: 'PV' },
    { word: 'ward off', meaning: ['đẩy lùi'], synonyms: '', topic: 2, type: 'PV' },
    { word: 'take in', meaning: ['chiêm ngưỡng', 'lừa gạt', 'tiếp thu', 'hiểu'], synonyms: 'admire, deceive, absorb, understand', topic: 2, type: 'PV' },
    { word: 'look after', meaning: ['chăm sóc'], synonyms: 'take care of, care for', topic: 2, type: 'PV' },
    { word: 'serve as', meaning: ['đóng vai trò'], synonyms: 'function as, act as', topic: 2, type: 'V' },

    // CHU DE 3
    // Verb: 1-39
    { word: 'recycle', meaning: ['tái chế'], synonyms: '', topic: 3, type: 'V' },
    { word: 'conserve', meaning: ['bảo tồn', 'sử dụng tiết kiệm'], synonyms: 'economize (on)', topic: 3, type: 'V' },
    { word: 'preserve', meaning: ['bảo tồn', 'giữ gìn', 'bảo quản (thực phẩm)'], synonyms: '', topic: 3, type: 'V' },
    { word: 'lower', meaning: ['giảm thiểu'], synonyms: 'reduce, decrease, lessen, mitigate, minimize, alleviate', topic: 3, type: 'V' },
    { word: 'reuse', meaning: ['tái sử dụng'], synonyms: '', topic: 3, type: 'V' },
    { word: 'offset', meaning: ['bù đắp'], synonyms: 'compensate (for), balance', topic: 3, type: 'V' },
    { word: 'emit', meaning: ['thải ra'], synonyms: 'release, discharge, give off', topic: 3, type: 'V' },
    { word: 'pollute', meaning: ['gây ô nhiễm'], synonyms: 'contaminate', topic: 3, type: 'V' },
    { word: 'recharge', meaning: ['sạc lại', 'tái tạo năng lượng'], synonyms: '', topic: 3, type: 'V' },
    { word: 'insulate', meaning: ['cách ly', 'cách nhiệt'], synonyms: '', topic: 3, type: 'V' },
    { word: 'harvest', meaning: ['thu hoạch', 'thu gom'], synonyms: '', topic: 3, type: 'V' },
    { word: 'dispose', meaning: ['vứt bỏ'], synonyms: 'discard, get rid of', topic: 3, type: 'V' },
    { word: 'generate', meaning: ['tạo ra'], synonyms: 'produce, manufacture', topic: 3, type: 'V' },
    { word: 'deplete', meaning: ['làm cạn kiệt'], synonyms: 'exhaust, use up', topic: 3, type: 'V' },
    { word: 'minimize', meaning: ['giảm thiểu'], synonyms: 'reduce, lessen, alleviate', topic: 3, type: 'V' },
    { word: 'switch', meaning: ['chuyển đổi'], synonyms: 'change (to), shift (to/towards)', topic: 3, type: 'V' },
    { word: 'invest', meaning: ['đầu tư'], synonyms: '', topic: 3, type: 'V' },
    { word: 'rebalance', meaning: ['cân bằng lại'], synonyms: 'restore the balance, redress the balance', topic: 3, type: 'V' },
    { word: 'ban', meaning: ['cấm'], synonyms: 'prohibit, forbid', topic: 3, type: 'V' },
    { word: 'promote', meaning: ['thúc đẩy'], synonyms: 'encourage, support, foster, boost', topic: 3, type: 'V' },
    { word: 'advocate', meaning: ['ủng hộ'], synonyms: 'support, stand for', topic: 3, type: 'V' },
    { word: 'implement', meaning: ['thực hiện'], synonyms: 'execute, carry out', topic: 3, type: 'V' },
    { word: 'monitor', meaning: ['giám sát'], synonyms: 'observe, supervise, oversee', topic: 3, type: 'V' },
    { word: 'regulate', meaning: ['kiểm soát', 'điều chỉnh'], synonyms: 'control, manage', topic: 3, type: 'V' },
    { word: 'manufacture', meaning: ['sản xuất'], synonyms: '', topic: 3, type: 'V' },
    { word: 'innovate', meaning: ['đổi mới'], synonyms: '', topic: 3, type: 'V' },
    { word: 'filter', meaning: ['lọc'], synonyms: 'purify', topic: 3, type: 'V' },
    { word: 'replant', meaning: ['trồng lại'], synonyms: '', topic: 3, type: 'V' },
    { word: 'renovate', meaning: ['cải tạo'], synonyms: 'repair, restore', topic: 3, type: 'V' },
    { word: 'reconnect', meaning: ['tái kết nối'], synonyms: '', topic: 3, type: 'V' },
    { word: 'embrace', meaning: ['đón nhận'], synonyms: '', topic: 3, type: 'V' },
    { word: 'sustain', meaning: ['duy trì'], synonyms: 'maintain, support', topic: 3, type: 'V' },
    { word: 'eliminate', meaning: ['loại bỏ'], synonyms: 'remove, get rid of, dispose of', topic: 3, type: 'V' },
    { word: 'trigger', meaning: ['gây ra'], synonyms: '', topic: 3, type: 'V' },
    { word: 'reassess', meaning: ['đánh giá lại'], synonyms: 'reevaluate, reconsider', topic: 3, type: 'V' },
    { word: 'modify', meaning: ['sửa đổi', 'điều chỉnh'], synonyms: '', topic: 3, type: 'V' },
    { word: 'enhance', meaning: ['nâng cao'], synonyms: 'improve, boost', topic: 3, type: 'V' },
    { word: 'restore', meaning: ['phục hồi'], synonyms: '', topic: 3, type: 'V' },
    // Noun: 1-30
    { word: 'sustainability', meaning: ['sự bền vững'], synonyms: '', topic: 3, type: 'N' },
    { word: 'emission', meaning: ['khí thải'], synonyms: 'discharge, release, output', topic: 3, type: 'N' },
    { word: 'pollution', meaning: ['sự ô nhiễm'], synonyms: 'contamination', topic: 3, type: 'N' },
    { word: 'conservation', meaning: ['sự bảo tồn'], synonyms: 'preservation, protection', topic: 3, type: 'N' },
    { word: 'ecosystem', meaning: ['hệ sinh thái'], synonyms: '', topic: 3, type: 'N' },
    { word: 'biodiversity', meaning: ['đa dạng sinh học'], synonyms: '', topic: 3, type: 'N' },
    { word: 'renewable energy', meaning: ['năng lượng tái tạo'], synonyms: 'sustainable energy, green energy', topic: 3, type: 'N' },
    { word: 'carbon footprint', meaning: ['lượng khí thải carbon'], synonyms: '', topic: 3, type: 'N' },
    { word: 'recycling', meaning: ['việc tái chế'], synonyms: '', topic: 3, type: 'N' },
    { word: 'compost', meaning: ['phân hữu cơ'], synonyms: '', topic: 3, type: 'N' },
    { word: 'consumption', meaning: ['sự tiêu thụ'], synonyms: '', topic: 3, type: 'N' },
    { word: 'natural resource', meaning: ['tài nguyên thiên nhiên'], synonyms: '', topic: 3, type: 'N' },
    { word: 'environment', meaning: ['môi trường'], synonyms: '', topic: 3, type: 'N' },
    { word: 'habitat', meaning: ['môi trường sống'], synonyms: '', topic: 3, type: 'N' },
    { word: 'deforestation', meaning: ['sự phá rừng'], synonyms: 'forest clearance', topic: 3, type: 'N' },
    { word: 'climate change', meaning: ['biến đổi khí hậu'], synonyms: '', topic: 3, type: 'N' },
    { word: 'organic farming', meaning: ['canh tác hữu cơ'], synonyms: '', topic: 3, type: 'N' },
    { word: 'hydro power', meaning: ['thuỷ điện'], synonyms: 'hydroelectric power', topic: 3, type: 'N' },
    { word: 'overconsumption', meaning: ['sự tiêu thụ quá mức'], synonyms: 'excessive use, overuse', topic: 3, type: 'N' },
    { word: 'landfill', meaning: ['bãi rác'], synonyms: '', topic: 3, type: 'N' },
    { word: 'efficiency', meaning: ['hiệu suất'], synonyms: 'productivity, effectiveness', topic: 3, type: 'N' },
    { word: 'quality', meaning: ['chất lượng'], synonyms: '', topic: 3, type: 'N' },
    { word: 'scarcity', meaning: ['sự khan hiếm'], synonyms: 'shortage, lack, insufficiency', topic: 3, type: 'N' },
    { word: 'fossil fuel', meaning: ['nhiên liệu hoá thạch'], synonyms: 'coal, oil and gas', topic: 3, type: 'N' },
    { word: 'reforestation', meaning: ['sự trồng rừng lại'], synonyms: 'afforestation', topic: 3, type: 'N' },
    { word: 'degradation', meaning: ['sự suy thoái'], synonyms: 'deterioration, decline', topic: 3, type: 'N' },
    { word: 'environmental awareness', meaning: ['nhận thức về môi trường'], synonyms: '', topic: 3, type: 'N' },
    { word: 'eco-consciousness', meaning: ['ý thức sinh thái'], synonyms: '', topic: 3, type: 'N' },
    { word: 'neutrality', meaning: ['tính trung lập'], synonyms: '', topic: 3, type: 'N' },
    { word: 'produce', meaning: ['nông sản'], synonyms: 'agricultural products', topic: 3, type: 'N' },

    // Adjective: 1-41
    { word: 'sustainable', meaning: ['bền vững'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'eco-friendly', meaning: ['thân thiện với môi trường'], synonyms: 'environmentally friendly, green', topic: 3, type: 'ADJ' },
    { word: 'renewable', meaning: ['có thể tái tạo'], synonyms: 'sustainable, inexhaustible', topic: 3, type: 'ADJ' },
    { word: 'recyclable', meaning: ['có thể tái chế'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'biodegradable', meaning: ['phân huỷ sinh học được'], synonyms: 'eco-friendly', topic: 3, type: 'ADJ' },
    { word: 'carbon-neutral', meaning: ['trung hoà carbon'], synonyms: 'net-zero carbon, carbon balanced', topic: 3, type: 'ADJ' },
    { word: 'toxic', meaning: ['độc hại'], synonyms: 'poisonous, hazardous', topic: 3, type: 'ADJ' },
    { word: 'harmful', meaning: ['có hại'], synonyms: 'damaging, detrimental', topic: 3, type: 'ADJ' },
    { word: 'excessive', meaning: ['quá mức'], synonyms: 'extreme, inordinate', topic: 3, type: 'ADJ' },
    { word: 'wasteful', meaning: ['lãng phí'], synonyms: 'extravagant', topic: 3, type: 'ADJ' },
    { word: 'environmentally-conscious', meaning: ['có ý thức về môi trường'], synonyms: 'eco-conscious', topic: 3, type: 'ADJ' },
    { word: 'hazardous', meaning: ['nguy hiểm'], synonyms: 'dangerous, risky, toxic', topic: 3, type: 'ADJ' },
    { word: 'contaminated', meaning: ['bị ô nhiễm'], synonyms: 'polluted, tainted', topic: 3, type: 'ADJ' },
    { word: 'efficient', meaning: ['hiệu quả'], synonyms: 'effective, productive', topic: 3, type: 'ADJ' },
    { word: 'energy-saving', meaning: ['tiết kiệm năng lượng'], synonyms: 'energy-efficient, economical', topic: 3, type: 'ADJ' },
    { word: 'long-lasting', meaning: ['bền lâu'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'responsible', meaning: ['có trách nhiệm'], synonyms: 'accountable, liable', topic: 3, type: 'ADJ' },
    { word: 'minimalist', meaning: ['tối giản'], synonyms: 'simple, basic', topic: 3, type: 'ADJ' },
    { word: 'resourceful', meaning: ['tháo vát'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'non-toxic', meaning: ['không độc hại'], synonyms: 'safe, harmless', topic: 3, type: 'ADJ' },
    { word: 'synthetic-free', meaning: ['không chứa chất tổng hợp'], synonyms: 'natural, organic', topic: 3, type: 'ADJ' },
    { word: 'pollution-free', meaning: ['không gây ô nhiễm'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'locally-sourced', meaning: ['có nguồn gốc địa phương'], synonyms: 'home-grown', topic: 3, type: 'ADJ' },
    { word: 'emission-free', meaning: ['không phát thải'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'durable', meaning: ['bền'], synonyms: 'long-lasting, sturdy', topic: 3, type: 'ADJ' },
    { word: 'climate-friendly', meaning: ['thân thiện với khí hậu'], synonyms: 'eco-friendly, sustainable', topic: 3, type: 'ADJ' },
    { word: 'solar-powered', meaning: ['chạy bằng năng lượng mặt trời'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'wind-powered', meaning: ['chạy bằng năng lượng gió'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'water-saving', meaning: ['tiết kiệm nước'], synonyms: 'water-efficient', topic: 3, type: 'ADJ' },
    { word: 'disposable', meaning: ['dùng một lần'], synonyms: 'single-use', topic: 3, type: 'ADJ' },
    { word: 'reusable', meaning: ['có thể tái sử dụng'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'low-impact', meaning: ['ít tác động'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'compostable', meaning: ['phân hủy thành phân hữu cơ'], synonyms: 'biodegradable, decomposable', topic: 3, type: 'ADJ' },
    { word: 'overused', meaning: ['bị sử dụng quá mức'], synonyms: 'exhausted, depleted', topic: 3, type: 'ADJ' },
    { word: 'forested', meaning: ['có rừng'], synonyms: 'wooded, tree-covered', topic: 3, type: 'ADJ' },
    { word: 'heat-trapping', meaning: ['giữ nhiệt'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'overcrowded', meaning: ['quá đông đúc'], synonyms: 'congested, packed', topic: 3, type: 'ADJ' },
    { word: 'urbanized', meaning: ['đô thị hóa'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'underdeveloped', meaning: ['kém phát triển'], synonyms: 'undeveloped, poor, destitute', topic: 3, type: 'ADJ' },
    { word: 'refillable', meaning: ['có thể đổ đầy lại'], synonyms: '', topic: 3, type: 'ADJ' },
    { word: 'eco-conscious', meaning: ['có ý thức về sinh thái'], synonyms: 'environmentally-conscious, eco-friendly', topic: 3, type: 'ADJ' },

    // PV: 1-46
    { word: 'cut down on', meaning: ['cắt giảm', 'giảm bớt'], synonyms: 'cut back on, reduce, minimize', topic: 3, type: 'PV' },
    { word: 'throw away', meaning: ['vứt bỏ'], synonyms: 'discard, dispose of, get rid of', topic: 3, type: 'PV' },
    { word: 'turn off', meaning: ['tắt (thiết bị)', 'làm mất hứng'], synonyms: 'switch off', topic: 3, type: 'PV' },
    { word: 'give up', meaning: ['từ bỏ'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'take in', meaning: ['hấp thụ', 'tiếp nhận'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'break down', meaning: ['phân huỷ tự nhiên', 'hỏng hóc', 'suy sụp'], synonyms: 'decompose, be out of order', topic: 3, type: 'PV' },
    { word: 'run out of', meaning: ['hết', 'cạn kiệt'], synonyms: 'use up, exhaust', topic: 3, type: 'PV' },
    { word: 'work towards', meaning: ['hướng tới'], synonyms: 'aim at, strive for', topic: 3, type: 'PV' },
    { word: 'look after', meaning: ['chăm sóc', 'bảo vệ'], synonyms: 'take care of, care for', topic: 3, type: 'PV' },
    { word: 'clean up', meaning: ['dọn dẹp'], synonyms: 'tidy up, clear up', topic: 3, type: 'PV' },
    { word: 'cut back on', meaning: ['cắt giảm'], synonyms: 'cut down on, reduce', topic: 3, type: 'PV' },
    { word: 'phase out', meaning: ['loại bỏ dần dần'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'set up', meaning: ['thiết lập'], synonyms: 'establish, found', topic: 3, type: 'PV' },
    { word: 'carry out', meaning: ['thực hiện'], synonyms: 'conduct, perform, execute', topic: 3, type: 'PV' },
    { word: 'get rid of', meaning: ['loại bỏ'], synonyms: 'eliminate, discard, throw away', topic: 3, type: 'PV' },
    { word: 'live off', meaning: ['sống nhờ vào'], synonyms: 'depend on, survive on', topic: 3, type: 'PV' },
    { word: 'grow up with', meaning: ['lớn lên với'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'bring down', meaning: ['làm giảm'], synonyms: 'reduce, lower', topic: 3, type: 'PV' },
    { word: 'give off', meaning: ['phát ra (khí, mùi)'], synonyms: 'emit, release', topic: 3, type: 'PV' },
    { word: 'stock up on', meaning: ['dự trữ'], synonyms: 'store up, accumulate', topic: 3, type: 'PV' },
    { word: 'sort out', meaning: ['phân loại', 'giải quyết'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'plug in', meaning: ['cắm điện'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'get back to', meaning: ['quay lại với'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'go ahead with', meaning: ['tiến hành'], synonyms: 'proceed with, press on with', topic: 3, type: 'PV' },
    { word: 'step up', meaning: ['tăng cường'], synonyms: 'increase, intensify', topic: 3, type: 'PV' },
    { word: 'move away from', meaning: ['tránh xa', 'chuyển khỏi'], synonyms: 'shift from, change away from', topic: 3, type: 'PV' },
    { word: 'wipe out', meaning: ['xóa sổ', 'tiêu diệt'], synonyms: 'eradicate', topic: 3, type: 'PV' },
    { word: 'drop off', meaning: ['giảm xuống'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'catch up on', meaning: ['bù đắp', 'bắt kịp'], synonyms: 'make up for, compensate', topic: 3, type: 'PV' },
    { word: 'come down with', meaning: ['mắc bệnh'], synonyms: 'fall ill with, go down with, contract', topic: 3, type: 'PV' },
    { word: 'end up', meaning: ['kết thúc (ở đâu đó)'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'turn down', meaning: ['giảm (âm lượng, nhiệt độ)', 'từ chối'], synonyms: 'refuse, reject', topic: 3, type: 'PV' },
    { word: 'go without', meaning: ['sống thiếu'], synonyms: 'do without, manage without', topic: 3, type: 'PV' },
    { word: 'look into', meaning: ['xem xét, điều tra'], synonyms: 'investigate', topic: 3, type: 'PV' },
    { word: 'break out', meaning: ['bùng phát'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'burn out', meaning: ['kiệt sức, cháy hết'], synonyms: 'exhaust, fatigue', topic: 3, type: 'PV' },
    { word: 'cancel out', meaning: ['triệt tiêu, xóa bỏ'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'get by', meaning: ['xoay xở để sống'], synonyms: 'manage', topic: 3, type: 'PV' },
    { word: 'give in', meaning: ['nhượng bộ', 'từ bỏ'], synonyms: 'surrender, yield', topic: 3, type: 'PV' },
    { word: 'log in', meaning: ['đăng nhập'], synonyms: 'sign in, access', topic: 3, type: 'PV' },
    { word: 'sign off', meaning: ['kết thúc, phê duyệt'], synonyms: 'approve, finish', topic: 3, type: 'PV' },
    { word: 'start off', meaning: ['bắt đầu'], synonyms: 'begin, commence', topic: 3, type: 'PV' },
    { word: 'stay on', meaning: ['ở lại lâu hơn'], synonyms: '', topic: 3, type: 'PV' },
    { word: 'take off', meaning: ['cất cánh', 'khởi sắc'], synonyms: 'rise, soar', topic: 3, type: 'PV' },
    { word: 'bring about', meaning: ['gây ra'], synonyms: 'cause, lead to', topic: 3, type: 'PV' },
    { word: 'substitute for', meaning: ['thay thế cho'], synonyms: 'replace', topic: 3, type: 'PV' },
    { word: 'phase in', meaning: ['đưa vào từ từ'], synonyms: '', topic: 3, type: 'PV' },

    //Chu De 4
    //Verb: 1-33:
    { word: 'urbanize', meaning: ['đô thị hóa'], synonyms: '', topic: 4, type: 'V' },
    { word: 'migrate', meaning: ['di cư (tạm thời)'], synonyms: 'move to, relocate to', topic: 4, type: 'V' },
    { word: 'expand', meaning: ['mở rộng'], synonyms: 'enlarge, extend', topic: 4, type: 'V' },
    { word: 'subsidize', meaning: ['trợ cấp'], synonyms: 'support financially, fund', topic: 4, type: 'V' },
    { word: 'resettle', meaning: ['tái định cư'], synonyms: 'relocate, move again', topic: 4, type: 'V' },
    { word: 'overcrowd', meaning: ['làm quá đông'], synonyms: '', topic: 4, type: 'V' },
    { word: 'develop', meaning: ['phát triển'], synonyms: 'grow, evolve, improve', topic: 4, type: 'V' },
    { word: 'construct', meaning: ['xây dựng'], synonyms: 'build, erect, put up', topic: 4, type: 'V' },
    { word: 'modernize', meaning: ['hiện đại hóa'], synonyms: 'upgrade, renovate', topic: 4, type: 'V' },
    { word: 'gentrify', meaning: ['cải tạo (khu phố theo hướng giàu có hơn)'], synonyms: '', topic: 4, type: 'V' },
    { word: 'transform', meaning: ['biến đổi'], synonyms: 'convert, change', topic: 4, type: 'V' },
    { word: 'densify', meaning: ['làm dày đặc hơn'], synonyms: 'intensify, compact', topic: 4, type: 'V' },
    { word: 'settle', meaning: ['định cư'], synonyms: 'inhabit, colonize', topic: 4, type: 'V' },
    { word: 'improve', meaning: ['cải thiện'], synonyms: 'enhance, upgrade', topic: 4, type: 'V' },
    { word: 'regenerate', meaning: ['tái tạo, phục hồi'], synonyms: 'renew, revitalize', topic: 4, type: 'V' },
    { word: 'upgrade', meaning: ['nâng cấp'], synonyms: 'improve, modernize', topic: 4, type: 'V' },
    { word: 'commute', meaning: ['đi lại (giữa nơi ở và nơi làm việc)'], synonyms: '', topic: 4, type: 'V' },
    { word: 'inhabit', meaning: ['cư trú'], synonyms: 'live in, reside', topic: 4, type: 'V' },
    { word: 'accommodate', meaning: ['cung cấp nơi ở', 'đáp ứng (nhu cầu)'], synonyms: '', topic: 4, type: 'V' },
    { word: 'distribute', meaning: ['phân phối'], synonyms: 'allocate, share', topic: 4, type: 'V' },
    { word: 'displace', meaning: ['thay thế, khiến ai đó phải chuyển chỗ'], synonyms: 'replace, relocate', topic: 4, type: 'V' },
    { word: 'demolish', meaning: ['phá hủy'], synonyms: 'destroy, tear down', topic: 4, type: 'V' },
    { word: 'design', meaning: ['thiết kế'], synonyms: '', topic: 4, type: 'V' },
    { word: 'integrate', meaning: ['tích hợp'], synonyms: 'combine, incorporate', topic: 4, type: 'V' },
    { word: 'allocate', meaning: ['phân bổ'], synonyms: 'distribute, assign', topic: 4, type: 'V' },
    { word: 'suffer', meaning: ['chịu đựng', 'trở nên tệ hơn'], synonyms: 'endure, worsen', topic: 4, type: 'V' },
    { word: 'regulate', meaning: ['điều chỉnh, kiểm soát'], synonyms: 'control, manage', topic: 4, type: 'V' },
    { word: 'maintain', meaning: ['duy trì'], synonyms: 'keep, preserve', topic: 4, type: 'V' },
    { word: 'spawn', meaning: ['tạo ra, sinh ra'], synonyms: 'generate, produce', topic: 4, type: 'V' },
    { word: 'combat', meaning: ['chống lại'], synonyms: 'fight against, tackle', topic: 4, type: 'V' },
    { word: 'minimize', meaning: ['giảm thiểu'], synonyms: 'reduce, lessen, lower', topic: 4, type: 'V' },
    { word: 'stimulate', meaning: ['kích thích'], synonyms: 'encourage, promote', topic: 4, type: 'V' },
    { word: 'revitalize', meaning: ['làm sống lại'], synonyms: 'renew, regenerate', topic: 4, type: 'V' },
    //Noun:1-30:
    { word: 'urbanisation', meaning: ['sự đô thị hóa'], synonyms: '', topic: 4, type: 'N' },
    { word: 'infrastructure', meaning: ['cơ sở hạ tầng'], synonyms: '', topic: 4, type: 'N' },
    { word: 'migration', meaning: ['sự di cư'], synonyms: 'movement, relocation', topic: 4, type: 'N' },
    { word: 'overpopulation', meaning: ['sự bùng nổ dân số'], synonyms: 'overcrowding, population explosion', topic: 4, type: 'N' },
    { word: 'congestion', meaning: ['sự tắc nghẽn'], synonyms: 'blockage, overcrowding', topic: 4, type: 'N' },
    { word: 'urban sprawl', meaning: ['sự mở rộng đô thị không kiểm soát'], synonyms: '', topic: 4, type: 'N' },
    { word: 'skyscraper', meaning: ['nhà chọc trời'], synonyms: 'high-rise building', topic: 4, type: 'N' },
    { word: 'slum', meaning: ['khu ổ chuột'], synonyms: '', topic: 4, type: 'N' },
    { word: 'suburb', meaning: ['ngoại ô'], synonyms: '', topic: 4, type: 'N' },
    { word: 'commuter', meaning: ['người đi làm xa nhà'], synonyms: '', topic: 4, type: 'N' },
    { word: 'development', meaning: ['sự phát triển'], synonyms: 'growth, evolution, expansion', topic: 4, type: 'N' },
    { word: 'pollution', meaning: ['sự ô nhiễm'], synonyms: 'contamination', topic: 4, type: 'N' },
    { word: 'gentrification', meaning: ['sự làm giàu khu phố'], synonyms: '', topic: 4, type: 'N' },
    { word: 'expansion', meaning: ['sự mở rộng'], synonyms: 'growth, extension', topic: 4, type: 'N' },
    { word: 'transportation', meaning: ['vận chuyển'], synonyms: 'transit, conveyance', topic: 4, type: 'N' },
    { word: 'public service', meaning: ['dịch vụ công cộng'], synonyms: '', topic: 4, type: 'N' },
    { word: 'sanitation', meaning: ['vệ sinh môi trường'], synonyms: '', topic: 4, type: 'N' },
    { word: 'irrigation', meaning: ['tưới tiêu'], synonyms: '', topic: 4, type: 'N' },
    { word: 'homelessness', meaning: ['tình trạng vô gia cư'], synonyms: '', topic: 4, type: 'N' },
    { word: 'shortage', meaning: ['sự thiếu hụt'], synonyms: 'lack, deficit', topic: 4, type: 'N' },
    { word: 'industrialisation', meaning: ['sự công nghiệp hóa'], synonyms: '', topic: 4, type: 'N' },
    { word: 'dweller', meaning: ['người cư trú'], synonyms: 'inhabitant, resident', topic: 4, type: 'N' },
    { word: 'living standard', meaning: ['mức sống'], synonyms: '', topic: 4, type: 'N' },
    { word: 'commercial zone', meaning: ['khu thương mại'], synonyms: 'business district, commercial area', topic: 4, type: 'N' },
    { word: 'density', meaning: ['mật độ'], synonyms: '', topic: 4, type: 'N' },
    { word: 'inequality', meaning: ['sự bất bình đẳng'], synonyms: 'disparity, discrepancy', topic: 4, type: 'N' },
    { word: 'public transit', meaning: ['giao thông công cộng'], synonyms: 'public transportation', topic: 4, type: 'N' },
    { word: 'commuting distance', meaning: ['khoảng cách đi làm'], synonyms: '', topic: 4, type: 'N' },
    { word: 'deficit', meaning: ['sự thiếu hụt'], synonyms: 'shortage, lack', topic: 4, type: 'N' },
    { word: 'urban decay', meaning: ['sự xuống cấp đô thị'], synonyms: '', topic: 4, type: 'N' },
    //ADJ:1-42:
    { word: 'urban', meaning: ['thuộc thành thị'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'rural', meaning: ['thuộc nông thôn'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'overcrowded', meaning: ['quá đông đúc'], synonyms: 'congested, packed', topic: 4, type: 'ADJ' },
    { word: 'sustainable', meaning: ['bền vững'], synonyms: 'eco-friendly, viable', topic: 4, type: 'ADJ' },
    { word: 'dense', meaning: ['dày đặc'], synonyms: 'thick, compact', topic: 4, type: 'ADJ' },
    { word: 'congested', meaning: ['bị tắc nghẽn'], synonyms: 'overcrowded', topic: 4, type: 'ADJ' },
    { word: 'affordable', meaning: ['giá cả phải chăng'], synonyms: 'reasonable, economical', topic: 4, type: 'ADJ' },
    { word: 'industrial', meaning: ['thuộc công nghiệp'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'populated', meaning: ['có dân cư'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'developing', meaning: ['đang phát triển'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'developed', meaning: ['phát triển'], synonyms: 'advanced', topic: 4, type: 'ADJ' },
    { word: 'urbanised', meaning: ['đô thị hóa'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'suburban', meaning: ['thuộc vùng ngoại ô'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'low-income', meaning: ['thu nhập thấp'], synonyms: 'poor', topic: 4, type: 'ADJ' },
    { word: 'high-rise', meaning: ['cao tầng'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'inner-city', meaning: ['trung tâm thành phố'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'inhabitable', meaning: ['có thể sinh sống'], synonyms: 'livable', topic: 4, type: 'ADJ' },
    { word: 'livable', meaning: ['đáng sống'], synonyms: 'habitable', topic: 4, type: 'ADJ' },
    { word: 'unplanned', meaning: ['không quy hoạch'], synonyms: 'spontaneous', topic: 4, type: 'ADJ' },
    { word: 'unregulated', meaning: ['không được kiểm soát'], synonyms: 'uncontrolled', topic: 4, type: 'ADJ' },
    { word: 'run-down', meaning: ['xuống cấp'], synonyms: 'dilapidated', topic: 4, type: 'ADJ' },
    { word: 'vibrant', meaning: ['sôi động'], synonyms: 'lively', topic: 4, type: 'ADJ' },
    { word: 'crowded', meaning: ['đông đúc'], synonyms: 'packed', topic: 4, type: 'ADJ' },
    { word: 'walkable', meaning: ['có thể đi bộ được'], synonyms: 'pedestrian-friendly', topic: 4, type: 'ADJ' },
    { word: 'accessible', meaning: ['dễ tiếp cận'], synonyms: 'reachable', topic: 4, type: 'ADJ' },
    { word: 'commuter-friendly', meaning: ['thân thiện với người đi làm'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'pollution-free', meaning: ['không ô nhiễm'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'eco-friendly', meaning: ['thân thiện với môi trường'], synonyms: 'environmentally friendly', topic: 4, type: 'ADJ' },
    { word: 'upgraded', meaning: ['được nâng cấp'], synonyms: 'renovated', topic: 4, type: 'ADJ' },
    { word: 'renovated', meaning: ['được cải tạo'], synonyms: 'restored', topic: 4, type: 'ADJ' },
    { word: 'inclusive', meaning: ['bao gồm'], synonyms: 'comprehensive', topic: 4, type: 'ADJ' },
    { word: 'multi-storey', meaning: ['nhiều tầng'], synonyms: 'multilevel', topic: 4, type: 'ADJ' },
    { word: 'compact', meaning: ['nhỏ gọn'], synonyms: 'dense', topic: 4, type: 'ADJ' },
    { word: 'transit-oriented', meaning: ['hướng tới giao thông công cộng'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'industrialized', meaning: ['đã công nghiệp hóa'], synonyms: 'developed', topic: 4, type: 'ADJ' },
    { word: 'secure', meaning: ['an toàn'], synonyms: 'safe', topic: 4, type: 'ADJ' },
    { word: 'underserved', meaning: ['thiếu dịch vụ'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'well-connected', meaning: ['kết nối tốt'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'remote', meaning: ['xa xôi'], synonyms: 'isolated', topic: 4, type: 'ADJ' },
    { word: 'marginalized', meaning: ['bị ra rìa'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'rehabilitated', meaning: ['được cải tạo lại'], synonyms: '', topic: 4, type: 'ADJ' },
    { word: 'dilapidated', meaning: ['xuống cấp trầm trọng'], synonyms: 'neglected, run-down', topic: 4, type: 'ADJ' },

    //PV:1-62:
    { word: 'adapt to', meaning: ['thích nghi với'], synonyms: 'adjust to, become accustomed to', topic: 4, type: 'PV' },
    { word: 'move in', meaning: ['chuyển đến'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'move out', meaning: ['chuyển đi'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'settle down', meaning: ['ổn định cuộc sống'], synonyms: 'start living a stable life', topic: 4, type: 'PV' },
    { word: 'build up', meaning: ['xây dựng', 'tăng lên'], synonyms: 'accumulate, increase, develop', topic: 4, type: 'PV' },
    { word: 'knock down', meaning: ['phá dỡ'], synonyms: 'demolish, tear down', topic: 4, type: 'PV' },
    { word: 'spread out', meaning: ['trải ra'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'fill up', meaning: ['làm đầy'], synonyms: 'pack, load', topic: 4, type: 'PV' },
    { word: 'drive up', meaning: ['làm tăng lên'], synonyms: 'increase, raise', topic: 4, type: 'PV' },
    { word: 'push out', meaning: ['đẩy ra ngoài'], synonyms: 'expel, displace', topic: 4, type: 'PV' },
    { word: 'tear down', meaning: ['phá bỏ'], synonyms: 'demolish, destroy', topic: 4, type: 'PV' },
    { word: 'run down', meaning: ['xuống cấp'], synonyms: 'deteriorate, decay', topic: 4, type: 'PV' },
    { word: 'clean up', meaning: ['dọn dẹp'], synonyms: 'tidy, remove waste', topic: 4, type: 'PV' },
    { word: 'grow out of', meaning: ['lớn vượt khỏi', 'không còn phù hợp'], synonyms: 'outgrow', topic: 4, type: 'PV' },
    { word: 'pack into', meaning: ['nhồi nhét vào'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'deal with', meaning: ['giải quyết'], synonyms: 'handle, address, cope with', topic: 4, type: 'PV' },
    { word: 'catch up with', meaning: ['đuổi kịp'], synonyms: 'keep up with, reach', topic: 4, type: 'PV' },
    { word: 'look for', meaning: ['tìm kiếm'], synonyms: 'search for, seek', topic: 4, type: 'PV' },
    { word: 'cordon off', meaning: ['phong tỏa'], synonyms: 'block, seal off', topic: 4, type: 'PV' },
    { word: 'cut off', meaning: ['cắt đứt'], synonyms: 'disconnect, isolate', topic: 4, type: 'PV' },
    { word: 'break down', meaning: ['hỏng hóc', 'suy sụp', 'phân tích'], synonyms: 'malfunction, collapse, analyze', topic: 4, type: 'PV' },
    { word: 'bring down', meaning: ['hạ thấp', 'làm giảm'], synonyms: 'reduce, lower', topic: 4, type: 'PV' },
    { word: 'shut down', meaning: ['đóng cửa', 'ngừng hoạt động'], synonyms: 'close, cease operation', topic: 4, type: 'PV' },
    { word: 'take up', meaning: ['chiếm (không gian, thời gian)'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'head for', meaning: ['tiến về hướng'], synonyms: 'go towards, move toward', topic: 4, type: 'PV' },
    { word: 'give way to', meaning: ['nhường chỗ cho'], synonyms: 'be replaced by, yield to', topic: 4, type: 'PV' },
    { word: 'put on', meaning: ['mặc vào', 'tăng (cân)', 'tổ chức'], synonyms: 'wear, gain, hold', topic: 4, type: 'PV' },
    { word: 'back up', meaning: ['hỗ trợ', 'sao lưu'], synonyms: 'support, save', topic: 4, type: 'PV' },
    { word: 'open up', meaning: ['mở ra', 'khai phá'], synonyms: 'unseal, unlock', topic: 4, type: 'PV' },
    { word: 'push up', meaning: ['đẩy lên'], synonyms: 'increase, raise', topic: 4, type: 'PV' },
    { word: 'level off', meaning: ['chững lại', 'ổn định'], synonyms: 'stabilize, flatten', topic: 4, type: 'PV' },
    { word: 'plug into', meaning: ['kết nối vào', 'cắm vào'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'zone off', meaning: ['chia khu vực'], synonyms: 'divide into zones', topic: 4, type: 'PV' },
    { word: 'follow up on', meaning: ['theo dõi', 'xử lý tiếp'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'live off', meaning: ['sống dựa vào'], synonyms: '', topic: 4, type: 'PV' },
    { word: 'phase out', meaning: ['loại bỏ dần'], synonyms: 'eliminate gradually', topic: 4, type: 'PV' },
    { word: 'carry out', meaning: ['tiến hành', 'thực hiện'], synonyms: 'conduct, implement, execute', topic: 4, type: 'PV' },
    { word: 'make up', meaning: ['chiếm', 'làm hòa', 'bịa đặt'], synonyms: 'account for, reconcile, fabricate', topic: 4, type: 'PV' },
    { word: 'focus on', meaning: ['tập trung vào'], synonyms: 'concentrate on', topic: 4, type: 'PV' },
    { word: 'adjust to', meaning: ['điều chỉnh, thích nghi'], synonyms: 'adapt to, accommodate to', topic: 4, type: 'PV' },
    { word: 'slow down', meaning: ['giảm tốc độ'], synonyms: 'decelerate', topic: 4, type: 'PV' },
    { word: 'look into', meaning: ['xem xét, điều tra'], synonyms: 'investigate, examine', topic: 4, type: 'PV' },
    { word: 'come up with', meaning: ['nghĩ ra, đưa ra'], synonyms: 'propose, suggest', topic: 4, type: 'PV' },
    { word: 'figure out', meaning: ['tìm ra, hiểu được'], synonyms: 'understand, solve', topic: 4, type: 'PV' },
    { word: 'keep up with', meaning: ['theo kịp'], synonyms: 'catch up with, stay updated with', topic: 4, type: 'PV' },

];
